/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Profile API
 * OpenAPI spec version: 1.0.0
 */
export interface AvatarItem {
  file_id?: string | null;
  mime?: string | null;
  size?: number | null;
  width?: number | null;
  height?: number | null;
  created_at?: string | null;
}

export interface AvatarsBlock {
  current?: AvatarItem | null;
  history?: AvatarItem[];
}

export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface PermissionsResponse {
  /** Можно ли отправить сообщение */
  you_can_send_message: boolean;
  /** Можно ли приглашать в паблики */
  you_can_public_invite_permission: boolean;
  /** Можно ли приглашать в беседы */
  you_can_group_invite_permission: boolean;
  /** Можно ли звонить */
  you_can_call_permission: boolean;
}

export interface RatingData {
  rating?: number | null;
  /** fine | unavailable | blocked | deleted */
  status?: string;
}

export interface ApiSchemasUserIdProfilePermissionsResponse {
  /** Можно ли находить пользователя */
  is_searchable?: boolean | null;
  /** Можно ли пересылать сообщения */
  allow_message_forwarding: boolean;
  /** Принимать сообщения от незнакомцев */
  allow_messages_from_non_contacts: boolean;
}

export interface RelationshipStatusResponse {
  /** target_user_id в контактах ли у current_user */
  is_target_in_contacts_of_current_user: boolean;
  /** current_user в контактах ли у пользователя */
  is_current_user_in_contacts_of_target: boolean;
  /** Заблокировал ли target_user_id у нашего пользователя */
  is_target_user_blocked_by_current_user: boolean;
  /** Заблокировал ли current_user у пользователя */
  is_current_user_in_blacklist_of_target: boolean;
}

export interface ProfileByUserIdData {
  /** ID пользователя */
  user_id: string;
  /** Логин */
  login?: string | null;
  /** Полное имя */
  full_name?: string | null;
  custom_name?: string | null;
  /** Биография */
  bio?: string | null;
  /** Подтвержденный (официальный) аккаунт */
  is_verified?: boolean | null;
  /** Системный аккаунт */
  is_system?: boolean | null;
  /** Рейтинг пользователя */
  rating: RatingData;
  /** Дата последнего посещения (null если скрыто) */
  last_seen_at?: string | null;
  /** Дата регистрации */
  created_at: string;
  /** Блок с текущей аватаркой и историей */
  avatars?: AvatarsBlock;
  /** Список сторис пользователя */
  stories?: unknown[];
  /** что МОЖЕТ текущий пользователь сделать с этим пользователем */
  permissions: PermissionsResponse;
  /** что настроено в профиле целевого пользователя */
  profile_permissions: ApiSchemasUserIdProfilePermissionsResponse;
  /** Статус отношений между текущим и целевым пользователем */
  relationship: RelationshipStatusResponse;
}

export interface ProfileByUserIdResponse {
  status: string;
  data: ProfileByUserIdData;
}

/**
 * Профили пользователей по user_id
 */
export type ProfileByUserIdsResponseData = {[key: string]: ProfileByUserIdData};

export interface ProfileByUserIdsResponse {
  /** Статус ответа */
  status: string;
  /** Профили пользователей по user_id */
  data: ProfileByUserIdsResponseData;
}

export interface WalletBalance {
  /** Тип валюты, например: btc или stable */
  currency: string;
  /**
   * Точный баланс
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  balance: string;
  /** Форматированный баланс для отображения (опционально) */
  display_balance?: number | null;
}

export interface ApiSchemasMeProfilePermissionsResponse {
  /** Можно ли находить пользователя */
  is_searchable: boolean;
  /** Можно ли пересылать сообщения */
  allow_message_forwarding: boolean;
  /** Принимать сообщения от незнакомцев */
  allow_messages_from_non_contacts: boolean;
  /** Показывать фото не-контактам */
  show_profile_photo_to_non_contacts: boolean;
  /**
   * Видимость 'был в сети' (0 - все, 1 - контакты, 2 - никто)
   * @minimum 0
   * @maximum 2
   */
  last_seen_visibility: number;
  /** Показывать био не-контактам */
  show_bio_to_non_contacts: boolean;
  /** Показывать сторисы не-контактам */
  show_stories_to_non_contacts: boolean;
  /**
   * Кто может приглашать в паблики (0 - все, 1 - контакты, 2 - никто)
   * @minimum 0
   * @maximum 2
   */
  public_invite_permission: number;
  /**
   * Кто может приглашать в беседы (0 - все, 1 - контакты, 2 - никто)
   * @minimum 0
   * @maximum 2
   */
  group_invite_permission: number;
  /**
   * Кто может звонить (0 - все, 1 - контакты, 2 - никто)
   * @minimum 0
   * @maximum 2
   */
  call_permission: number;
  /** Автоудаление аккаунта через X дней */
  auto_delete_after_days?: number | null;
}

export interface ProfileData {
  /** ID пользователя */
  user_id: string;
  /**
   * Логин
   * @minLength 3
   * @maxLength 32
   */
  login: string;
  /** Полное имя */
  full_name?: string | null;
  /** Биография */
  bio?: string | null;
  /** Подтвержденный (официальный) аккаунт */
  is_verified?: boolean | null;
  /** Рейтинг пользователя */
  rating: RatingData;
  /** Список доступных балансов пользователя */
  balances: WalletBalance[];
  /** Дата регистрации */
  created_at: string;
  /** Блок с текущей аватаркой и историей */
  avatars?: AvatarsBlock;
  /** Список сторис пользователя */
  stories?: unknown[];
  /** что настроено в профиле целевого пользователя */
  profile_permissions: ApiSchemasMeProfilePermissionsResponse;
}

export interface ProfilePermissionsRequest {
  /** Можно ли находить пользователя */
  is_searchable?: boolean | null;
  /** Можно ли пересылать сообщения */
  allow_message_forwarding?: boolean | null;
  /** Принимать сообщения от незнакомцев */
  allow_messages_from_non_contacts?: boolean | null;
  /** Показывать фото не-контактам */
  show_profile_photo_to_non_contacts?: boolean | null;
  /** Видимость 'был в сети' (0 - все, 1 - контакты, 2 - никто) */
  last_seen_visibility?: number | null;
  /** Показывать био не-контактам */
  show_bio_to_non_contacts?: boolean | null;
  /** Показывать сторисы не-контактам */
  show_stories_to_non_contacts?: boolean | null;
  /** Кто может приглашать в паблики (0 - все, 1 - контакты, 2 - никто) */
  public_invite_permission?: number | null;
  /** Кто может приглашать в беседы (0 - все, 1 - контакты, 2 - никто) */
  group_invite_permission?: number | null;
  /** Кто может звонить (0 - все, 1 - контакты, 2 - никто) */
  call_permission?: number | null;
  /** Автоудаление аккаунта через X дней */
  auto_delete_after_days?: number | null;
}

export interface ProfileResponse {
  status: string;
  data: ProfileData;
}

export interface ProfileUpdateRequest {
  /** Полное имя */
  full_name?: string | null;
  /** Биография */
  bio?: string | null;
  /** что настроено в профиле целевого пользователя */
  profile_permissions?: ProfilePermissionsRequest;
}

export interface UserProfileRequest {
  user_id: string;
  current_user: string;
  full_profile: boolean;
  with_permissions: boolean;
}

export interface UserProfilesRequest {
  user_id: string;
  user_ids: string[];
  full_profile: boolean;
  with_permissions: boolean;
}

