/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Profile V2 API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  HTTPValidationError,
  MeEditRequest,
  PrivacyGetResponse,
  ProfileByUserIdResponse,
  ProfileByUserIdsResponse,
  UserProfileRequest,
  UserProfilesRequest
} from '../profile-service-v2.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get My Profile
 */
export const getMyProfileMeGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivacyGetResponse>(
      {url: `/v2/profile/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyProfileMeGetQueryKey = () => {
    return [
    `/v2/profile/me`
    ] as const;
    }

    
export const getGetMyProfileMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyProfileMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyProfileMeGet>>> = ({ signal }) => getMyProfileMeGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyProfileMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMyProfileMeGet>>>
export type GetMyProfileMeGetQueryError = ErrorType<unknown>


export function useGetMyProfileMeGet<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProfileMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMyProfileMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProfileMeGet<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProfileMeGet>>,
          TError,
          Awaited<ReturnType<typeof getMyProfileMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProfileMeGet<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Profile
 */

export function useGetMyProfileMeGet<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyProfileMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetMyProfileMeGetSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyProfileMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyProfileMeGet>>> = ({ signal }) => getMyProfileMeGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyProfileMeGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMyProfileMeGet>>>
export type GetMyProfileMeGetSuspenseQueryError = ErrorType<unknown>


export function useGetMyProfileMeGetSuspense<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProfileMeGetSuspense<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyProfileMeGetSuspense<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Profile
 */

export function useGetMyProfileMeGetSuspense<TData = Awaited<ReturnType<typeof getMyProfileMeGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyProfileMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyProfileMeGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Edit Profile
 */
export const editProfileEditPut = (
    meEditRequest: BodyType<MeEditRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v2/profile/edit`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: meEditRequest, signal
    },
      options);
    }
  


export const getEditProfileEditPutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editProfileEditPut>>, TError,{data: BodyType<MeEditRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof editProfileEditPut>>, TError,{data: BodyType<MeEditRequest>}, TContext> => {

const mutationKey = ['editProfileEditPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editProfileEditPut>>, {data: BodyType<MeEditRequest>}> = (props) => {
          const {data} = props ?? {};

          return  editProfileEditPut(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EditProfileEditPutMutationResult = NonNullable<Awaited<ReturnType<typeof editProfileEditPut>>>
    export type EditProfileEditPutMutationBody = BodyType<MeEditRequest>
    export type EditProfileEditPutMutationError = ErrorType<unknown>

    /**
 * @summary Edit Profile
 */
export const useEditProfileEditPut = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editProfileEditPut>>, TError,{data: BodyType<MeEditRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editProfileEditPut>>,
        TError,
        {data: BodyType<MeEditRequest>},
        TContext
      > => {
      return useMutation(getEditProfileEditPutMutationOptions(options), queryClient);
    }
    /**
 * @summary Get User Profile By User Id
 */
export const getUserProfileByUserIdUserIdGet = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProfileByUserIdResponse>(
      {url: `/v2/profile/${userId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUserProfileByUserIdUserIdGetQueryKey = (userId: string,) => {
    return [
    `/v2/profile/${userId}`
    ] as const;
    }

    
export const getGetUserProfileByUserIdUserIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProfileByUserIdUserIdGetQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>> = ({ signal }) => getUserProfileByUserIdUserIdGet(userId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProfileByUserIdUserIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>>
export type GetUserProfileByUserIdUserIdGetQueryError = ErrorType<unknown>


export function useGetUserProfileByUserIdUserIdGet<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileByUserIdUserIdGet<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileByUserIdUserIdGet<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Profile By User Id
 */

export function useGetUserProfileByUserIdUserIdGet<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProfileByUserIdUserIdGetQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get User Profile By User Id
 */
export const prefetchGetUserProfileByUserIdUserIdGetQuery = async <TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 queryClient: QueryClient, userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetUserProfileByUserIdUserIdGetQueryOptions(userId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



export const getGetUserProfileByUserIdUserIdGetSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(userId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProfileByUserIdUserIdGetQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>> = ({ signal }) => getUserProfileByUserIdUserIdGet(userId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProfileByUserIdUserIdGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>>
export type GetUserProfileByUserIdUserIdGetSuspenseQueryError = ErrorType<unknown>


export function useGetUserProfileByUserIdUserIdGetSuspense<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileByUserIdUserIdGetSuspense<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfileByUserIdUserIdGetSuspense<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Profile By User Id
 */

export function useGetUserProfileByUserIdUserIdGetSuspense<TData = Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProfileByUserIdUserIdGetSuspenseQueryOptions(userId,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get User Profile By User Id
 */
export const getUserProfileByUserIdUserIdInternalPost = (
    userProfileRequest: BodyType<UserProfileRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProfileByUserIdResponse>(
      {url: `/v2/profile/user_id/internal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userProfileRequest, signal
    },
      options);
    }
  


export const getGetUserProfileByUserIdUserIdInternalPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdInternalPost>>, TError,{data: BodyType<UserProfileRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdInternalPost>>, TError,{data: BodyType<UserProfileRequest>}, TContext> => {

const mutationKey = ['getUserProfileByUserIdUserIdInternalPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdInternalPost>>, {data: BodyType<UserProfileRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getUserProfileByUserIdUserIdInternalPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetUserProfileByUserIdUserIdInternalPostMutationResult = NonNullable<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdInternalPost>>>
    export type GetUserProfileByUserIdUserIdInternalPostMutationBody = BodyType<UserProfileRequest>
    export type GetUserProfileByUserIdUserIdInternalPostMutationError = ErrorType<unknown>

    /**
 * @summary Get User Profile By User Id
 */
export const useGetUserProfileByUserIdUserIdInternalPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserProfileByUserIdUserIdInternalPost>>, TError,{data: BodyType<UserProfileRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUserProfileByUserIdUserIdInternalPost>>,
        TError,
        {data: BodyType<UserProfileRequest>},
        TContext
      > => {
      return useMutation(getGetUserProfileByUserIdUserIdInternalPostMutationOptions(options), queryClient);
    }
    /**
 * @summary [internal] Get Profiles Internal
 */
export const getProfilesInternalUserIdsInternalPost = (
    userProfilesRequest: BodyType<UserProfilesRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ProfileByUserIdsResponse>(
      {url: `/v2/profile/user_ids/internal`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userProfilesRequest, signal
    },
      options);
    }
  


export const getGetProfilesInternalUserIdsInternalPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getProfilesInternalUserIdsInternalPost>>, TError,{data: BodyType<UserProfilesRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getProfilesInternalUserIdsInternalPost>>, TError,{data: BodyType<UserProfilesRequest>}, TContext> => {

const mutationKey = ['getProfilesInternalUserIdsInternalPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getProfilesInternalUserIdsInternalPost>>, {data: BodyType<UserProfilesRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getProfilesInternalUserIdsInternalPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetProfilesInternalUserIdsInternalPostMutationResult = NonNullable<Awaited<ReturnType<typeof getProfilesInternalUserIdsInternalPost>>>
    export type GetProfilesInternalUserIdsInternalPostMutationBody = BodyType<UserProfilesRequest>
    export type GetProfilesInternalUserIdsInternalPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary [internal] Get Profiles Internal
 */
export const useGetProfilesInternalUserIdsInternalPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getProfilesInternalUserIdsInternalPost>>, TError,{data: BodyType<UserProfilesRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getProfilesInternalUserIdsInternalPost>>,
        TError,
        {data: BodyType<UserProfilesRequest>},
        TContext
      > => {
      return useMutation(getGetProfilesInternalUserIdsInternalPostMutationOptions(options), queryClient);
    }
    