/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * rating_service API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UsersRatingsRequest,
  UsersRatingsResponse
} from '../rating-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Получение рейтингов сразу для нескольких пользователей
 * @summary Get Users Ratings
 */
export const getUsersRatingsInternalUsersPost = (
    usersRatingsRequest: BodyType<UsersRatingsRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UsersRatingsResponse>(
      {url: `/v1/rating/internal/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: usersRatingsRequest, signal
    },
      options);
    }
  


export const getGetUsersRatingsInternalUsersPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUsersRatingsInternalUsersPost>>, TError,{data: BodyType<UsersRatingsRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getUsersRatingsInternalUsersPost>>, TError,{data: BodyType<UsersRatingsRequest>}, TContext> => {

const mutationKey = ['getUsersRatingsInternalUsersPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUsersRatingsInternalUsersPost>>, {data: BodyType<UsersRatingsRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getUsersRatingsInternalUsersPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetUsersRatingsInternalUsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof getUsersRatingsInternalUsersPost>>>
    export type GetUsersRatingsInternalUsersPostMutationBody = BodyType<UsersRatingsRequest>
    export type GetUsersRatingsInternalUsersPostMutationError = ErrorType<unknown>

    /**
 * @summary Get Users Ratings
 */
export const useGetUsersRatingsInternalUsersPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUsersRatingsInternalUsersPost>>, TError,{data: BodyType<UsersRatingsRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUsersRatingsInternalUsersPost>>,
        TError,
        {data: BodyType<UsersRatingsRequest>},
        TContext
      > => {
      return useMutation(getGetUsersRatingsInternalUsersPostMutationOptions(options), queryClient);
    }
    