/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiSchemasBotRegisterRequest,
  ApiSchemasBotRegisterResponse,
  ApiSchemasRegisterRegisterRequest,
  ApiSchemasRegisterRegisterResponse,
  BaseResponse,
  BotListResponse,
  ChangePasswordRequest,
  GetUserBotsBotListGetParams,
  IOSLinkResponse,
  InternalSessionsListInternalSessionsListGetParams,
  LoginCodeRequest,
  LoginRequest,
  LoginResponse,
  SessionsListResponse,
  TokenRefreshRequest,
  TokenRefreshResponse,
  UpdatePushTokenSessionsUpdatePushTokenPostParams,
  VerifyCodeRequest
} from '../auth-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Login
 */
export const loginLoginPasswordPost = (
    loginRequest: BodyType<LoginRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LoginResponse>(
      {url: `/v1/auth/login/password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginLoginPasswordPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginLoginPasswordPost>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginLoginPasswordPost>>, TError,{data: BodyType<LoginRequest>}, TContext> => {

const mutationKey = ['loginLoginPasswordPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginLoginPasswordPost>>, {data: BodyType<LoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  loginLoginPasswordPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginLoginPasswordPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginLoginPasswordPost>>>
    export type LoginLoginPasswordPostMutationBody = BodyType<LoginRequest>
    export type LoginLoginPasswordPostMutationError = ErrorType<unknown>

    /**
 * @summary Login
 */
export const useLoginLoginPasswordPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginLoginPasswordPost>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginLoginPasswordPost>>,
        TError,
        {data: BodyType<LoginRequest>},
        TContext
      > => {
      return useMutation(getLoginLoginPasswordPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Login Code
 */
export const loginCodeLoginCodePost = (
    loginCodeRequest: BodyType<LoginCodeRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/login/code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginCodeRequest, signal
    },
      options);
    }
  


export const getLoginCodeLoginCodePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, TError,{data: BodyType<LoginCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, TError,{data: BodyType<LoginCodeRequest>}, TContext> => {

const mutationKey = ['loginCodeLoginCodePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, {data: BodyType<LoginCodeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  loginCodeLoginCodePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginCodeLoginCodePostMutationResult = NonNullable<Awaited<ReturnType<typeof loginCodeLoginCodePost>>>
    export type LoginCodeLoginCodePostMutationBody = BodyType<LoginCodeRequest>
    export type LoginCodeLoginCodePostMutationError = ErrorType<unknown>

    /**
 * @summary Login Code
 */
export const useLoginCodeLoginCodePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, TError,{data: BodyType<LoginCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginCodeLoginCodePost>>,
        TError,
        {data: BodyType<LoginCodeRequest>},
        TContext
      > => {
      return useMutation(getLoginCodeLoginCodePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Verify Code
 */
export const verifyCodeLoginVerifyCodePost = (
    verifyCodeRequest: BodyType<VerifyCodeRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LoginResponse>(
      {url: `/v1/auth/login/verify_code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyCodeRequest, signal
    },
      options);
    }
  


export const getVerifyCodeLoginVerifyCodePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCodeLoginVerifyCodePost>>, TError,{data: BodyType<VerifyCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof verifyCodeLoginVerifyCodePost>>, TError,{data: BodyType<VerifyCodeRequest>}, TContext> => {

const mutationKey = ['verifyCodeLoginVerifyCodePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyCodeLoginVerifyCodePost>>, {data: BodyType<VerifyCodeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  verifyCodeLoginVerifyCodePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyCodeLoginVerifyCodePostMutationResult = NonNullable<Awaited<ReturnType<typeof verifyCodeLoginVerifyCodePost>>>
    export type VerifyCodeLoginVerifyCodePostMutationBody = BodyType<VerifyCodeRequest>
    export type VerifyCodeLoginVerifyCodePostMutationError = ErrorType<unknown>

    /**
 * @summary Verify Code
 */
export const useVerifyCodeLoginVerifyCodePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyCodeLoginVerifyCodePost>>, TError,{data: BodyType<VerifyCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyCodeLoginVerifyCodePost>>,
        TError,
        {data: BodyType<VerifyCodeRequest>},
        TContext
      > => {
      return useMutation(getVerifyCodeLoginVerifyCodePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Register
 */
export const registerRegisterPost = (
    apiSchemasRegisterRegisterRequest: BodyType<ApiSchemasRegisterRegisterRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiSchemasRegisterRegisterResponse>(
      {url: `/v1/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: apiSchemasRegisterRegisterRequest, signal
    },
      options);
    }
  


export const getRegisterRegisterPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerRegisterPost>>, TError,{data: BodyType<ApiSchemasRegisterRegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerRegisterPost>>, TError,{data: BodyType<ApiSchemasRegisterRegisterRequest>}, TContext> => {

const mutationKey = ['registerRegisterPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerRegisterPost>>, {data: BodyType<ApiSchemasRegisterRegisterRequest>}> = (props) => {
          const {data} = props ?? {};

          return  registerRegisterPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterRegisterPostMutationResult = NonNullable<Awaited<ReturnType<typeof registerRegisterPost>>>
    export type RegisterRegisterPostMutationBody = BodyType<ApiSchemasRegisterRegisterRequest>
    export type RegisterRegisterPostMutationError = ErrorType<unknown>

    /**
 * @summary Register
 */
export const useRegisterRegisterPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerRegisterPost>>, TError,{data: BodyType<ApiSchemasRegisterRegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerRegisterPost>>,
        TError,
        {data: BodyType<ApiSchemasRegisterRegisterRequest>},
        TContext
      > => {
      return useMutation(getRegisterRegisterPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Do Refresh Token
 */
export const doRefreshTokenTokenRefreshPost = (
    tokenRefreshRequest: BodyType<TokenRefreshRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenRefreshResponse>(
      {url: `/v1/auth/token/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRefreshRequest, signal
    },
      options);
    }
  


export const getDoRefreshTokenTokenRefreshPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof doRefreshTokenTokenRefreshPost>>, TError,{data: BodyType<TokenRefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof doRefreshTokenTokenRefreshPost>>, TError,{data: BodyType<TokenRefreshRequest>}, TContext> => {

const mutationKey = ['doRefreshTokenTokenRefreshPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof doRefreshTokenTokenRefreshPost>>, {data: BodyType<TokenRefreshRequest>}> = (props) => {
          const {data} = props ?? {};

          return  doRefreshTokenTokenRefreshPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DoRefreshTokenTokenRefreshPostMutationResult = NonNullable<Awaited<ReturnType<typeof doRefreshTokenTokenRefreshPost>>>
    export type DoRefreshTokenTokenRefreshPostMutationBody = BodyType<TokenRefreshRequest>
    export type DoRefreshTokenTokenRefreshPostMutationError = ErrorType<unknown>

    /**
 * @summary Do Refresh Token
 */
export const useDoRefreshTokenTokenRefreshPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof doRefreshTokenTokenRefreshPost>>, TError,{data: BodyType<TokenRefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof doRefreshTokenTokenRefreshPost>>,
        TError,
        {data: BodyType<TokenRefreshRequest>},
        TContext
      > => {
      return useMutation(getDoRefreshTokenTokenRefreshPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Request Password Reset
 */
export const requestPasswordResetPasswordResetPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/password/reset`, method: 'POST', signal
    },
      options);
    }
  


export const getRequestPasswordResetPasswordResetPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, TError,void, TContext> => {

const mutationKey = ['requestPasswordResetPasswordResetPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, void> = () => {
          

          return  requestPasswordResetPasswordResetPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RequestPasswordResetPasswordResetPostMutationResult = NonNullable<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>>
    
    export type RequestPasswordResetPasswordResetPostMutationError = ErrorType<unknown>

    /**
 * @summary Request Password Reset
 */
export const useRequestPasswordResetPasswordResetPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRequestPasswordResetPasswordResetPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Confirm Password Reset
 */
export const confirmPasswordResetPasswordResetConfirmPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/password/reset/confirm`, method: 'POST', signal
    },
      options);
    }
  


export const getConfirmPasswordResetPasswordResetConfirmPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, TError,void, TContext> => {

const mutationKey = ['confirmPasswordResetPasswordResetConfirmPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, void> = () => {
          

          return  confirmPasswordResetPasswordResetConfirmPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmPasswordResetPasswordResetConfirmPostMutationResult = NonNullable<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>>
    
    export type ConfirmPasswordResetPasswordResetConfirmPostMutationError = ErrorType<unknown>

    /**
 * @summary Confirm Password Reset
 */
export const useConfirmPasswordResetPasswordResetConfirmPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getConfirmPasswordResetPasswordResetConfirmPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Change Password
 */
export const changePasswordPasswordChangePost = (
    changePasswordRequest: BodyType<ChangePasswordRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/password/change`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequest, signal
    },
      options);
    }
  


export const getChangePasswordPasswordChangePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext> => {

const mutationKey = ['changePasswordPasswordChangePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, {data: BodyType<ChangePasswordRequest>}> = (props) => {
          const {data} = props ?? {};

          return  changePasswordPasswordChangePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordPasswordChangePostMutationResult = NonNullable<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>>
    export type ChangePasswordPasswordChangePostMutationBody = BodyType<ChangePasswordRequest>
    export type ChangePasswordPasswordChangePostMutationError = ErrorType<unknown>

    /**
 * @summary Change Password
 */
export const useChangePasswordPasswordChangePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePasswordPasswordChangePost>>,
        TError,
        {data: BodyType<ChangePasswordRequest>},
        TContext
      > => {
      return useMutation(getChangePasswordPasswordChangePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Bot Register
 */
export const botRegisterBotRegisterPost = (
    apiSchemasBotRegisterRequest: BodyType<ApiSchemasBotRegisterRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ApiSchemasBotRegisterResponse>(
      {url: `/v1/auth/bot/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: apiSchemasBotRegisterRequest, signal
    },
      options);
    }
  


export const getBotRegisterBotRegisterPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botRegisterBotRegisterPost>>, TError,{data: BodyType<ApiSchemasBotRegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof botRegisterBotRegisterPost>>, TError,{data: BodyType<ApiSchemasBotRegisterRequest>}, TContext> => {

const mutationKey = ['botRegisterBotRegisterPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof botRegisterBotRegisterPost>>, {data: BodyType<ApiSchemasBotRegisterRequest>}> = (props) => {
          const {data} = props ?? {};

          return  botRegisterBotRegisterPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BotRegisterBotRegisterPostMutationResult = NonNullable<Awaited<ReturnType<typeof botRegisterBotRegisterPost>>>
    export type BotRegisterBotRegisterPostMutationBody = BodyType<ApiSchemasBotRegisterRequest>
    export type BotRegisterBotRegisterPostMutationError = ErrorType<unknown>

    /**
 * @summary Bot Register
 */
export const useBotRegisterBotRegisterPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof botRegisterBotRegisterPost>>, TError,{data: BodyType<ApiSchemasBotRegisterRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof botRegisterBotRegisterPost>>,
        TError,
        {data: BodyType<ApiSchemasBotRegisterRequest>},
        TContext
      > => {
      return useMutation(getBotRegisterBotRegisterPostMutationOptions(options), queryClient);
    }
    /**
 * Получение списка ботов текущего пользователя с пагинацией (offset/limit)
 * @summary Get User Bots
 */
export const getUserBotsBotListGet = (
    params?: GetUserBotsBotListGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BotListResponse>(
      {url: `/v1/auth/bot/list`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetUserBotsBotListGetQueryKey = (params?: GetUserBotsBotListGetParams,) => {
    return [
    `/v1/auth/bot/list`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUserBotsBotListGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError = ErrorType<unknown>>(params?: GetUserBotsBotListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserBotsBotListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBotsBotListGet>>> = ({ signal }) => getUserBotsBotListGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserBotsBotListGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserBotsBotListGet>>>
export type GetUserBotsBotListGetQueryError = ErrorType<unknown>


export function useGetUserBotsBotListGet<TData = Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError = ErrorType<unknown>>(
 params: undefined |  GetUserBotsBotListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBotsBotListGet>>,
          TError,
          Awaited<ReturnType<typeof getUserBotsBotListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBotsBotListGet<TData = Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError = ErrorType<unknown>>(
 params?: GetUserBotsBotListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserBotsBotListGet>>,
          TError,
          Awaited<ReturnType<typeof getUserBotsBotListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserBotsBotListGet<TData = Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError = ErrorType<unknown>>(
 params?: GetUserBotsBotListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Bots
 */

export function useGetUserBotsBotListGet<TData = Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError = ErrorType<unknown>>(
 params?: GetUserBotsBotListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBotsBotListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserBotsBotListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Возвращает список всех активных сессий текущего пользователя.
 * @summary Sessions List
 */
export const sessionsListSessionsListGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SessionsListResponse>(
      {url: `/v1/auth/sessions/list`, method: 'GET', signal
    },
      options);
    }
  



export const getSessionsListSessionsListGetQueryKey = () => {
    return [
    `/v1/auth/sessions/list`
    ] as const;
    }

    
export const getSessionsListSessionsListGetQueryOptions = <TData = Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSessionsListSessionsListGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sessionsListSessionsListGet>>> = ({ signal }) => sessionsListSessionsListGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SessionsListSessionsListGetQueryResult = NonNullable<Awaited<ReturnType<typeof sessionsListSessionsListGet>>>
export type SessionsListSessionsListGetQueryError = ErrorType<unknown>


export function useSessionsListSessionsListGet<TData = Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionsListSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof sessionsListSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionsListSessionsListGet<TData = Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sessionsListSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof sessionsListSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSessionsListSessionsListGet<TData = Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sessions List
 */

export function useSessionsListSessionsListGet<TData = Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sessionsListSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSessionsListSessionsListGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Деактивирует (отключает) конкретную сессию пользователя.
 * @summary Revoke Session
 */
export const revokeSessionSessionsRevokeSessionIdPost = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/sessions/revoke/${sessionId}`, method: 'POST', signal
    },
      options);
    }
  


export const getRevokeSessionSessionsRevokeSessionIdPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, TError,{sessionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, TError,{sessionId: string}, TContext> => {

const mutationKey = ['revokeSessionSessionsRevokeSessionIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, {sessionId: string}> = (props) => {
          const {sessionId} = props ?? {};

          return  revokeSessionSessionsRevokeSessionIdPost(sessionId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeSessionSessionsRevokeSessionIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>>
    
    export type RevokeSessionSessionsRevokeSessionIdPostMutationError = ErrorType<unknown>

    /**
 * @summary Revoke Session
 */
export const useRevokeSessionSessionsRevokeSessionIdPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, TError,{sessionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>,
        TError,
        {sessionId: string},
        TContext
      > => {
      return useMutation(getRevokeSessionSessionsRevokeSessionIdPostMutationOptions(options), queryClient);
    }
    /**
 * Деактивирует все сессии пользователя, кроме текущей.
Новая сессия должна быть доверенной (существовать не менее N дней).
 * @summary Revoke All Except Current
 */
export const revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/sessions/revoke_all_except_current`, method: 'POST', signal
    },
      options);
    }
  


export const getRevokeAllExceptCurrentSessionsRevokeAllExceptCurrentPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost>>, TError,void, TContext> => {

const mutationKey = ['revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost>>, void> = () => {
          

          return  revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeAllExceptCurrentSessionsRevokeAllExceptCurrentPostMutationResult = NonNullable<Awaited<ReturnType<typeof revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost>>>
    
    export type RevokeAllExceptCurrentSessionsRevokeAllExceptCurrentPostMutationError = ErrorType<unknown>

    /**
 * @summary Revoke All Except Current
 */
export const useRevokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeAllExceptCurrentSessionsRevokeAllExceptCurrentPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRevokeAllExceptCurrentSessionsRevokeAllExceptCurrentPostMutationOptions(options), queryClient);
    }
    /**
 * Возвращает список всех активных сессий текущего пользователя.
 * @summary Internal Sessions List
 */
export const internalSessionsListInternalSessionsListGet = (
    params: InternalSessionsListInternalSessionsListGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/auth/internal/sessions/list`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getInternalSessionsListInternalSessionsListGetQueryKey = (params?: InternalSessionsListInternalSessionsListGetParams,) => {
    return [
    `/v1/auth/internal/sessions/list`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getInternalSessionsListInternalSessionsListGetQueryOptions = <TData = Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError = ErrorType<unknown>>(params: InternalSessionsListInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalSessionsListInternalSessionsListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>> = ({ signal }) => internalSessionsListInternalSessionsListGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalSessionsListInternalSessionsListGetQueryResult = NonNullable<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>>
export type InternalSessionsListInternalSessionsListGetQueryError = ErrorType<unknown>


export function useInternalSessionsListInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalSessionsListInternalSessionsListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalSessionsListInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalSessionsListInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalSessionsListInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalSessionsListInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Internal Sessions List
 */

export function useInternalSessionsListInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalSessionsListInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalSessionsListInternalSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalSessionsListInternalSessionsListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Push Token
 */
export const updatePushTokenSessionsUpdatePushTokenPost = (
    params: UpdatePushTokenSessionsUpdatePushTokenPostParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/sessions/update_push_token`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getUpdatePushTokenSessionsUpdatePushTokenPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, TError,{params: UpdatePushTokenSessionsUpdatePushTokenPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, TError,{params: UpdatePushTokenSessionsUpdatePushTokenPostParams}, TContext> => {

const mutationKey = ['updatePushTokenSessionsUpdatePushTokenPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, {params: UpdatePushTokenSessionsUpdatePushTokenPostParams}> = (props) => {
          const {params} = props ?? {};

          return  updatePushTokenSessionsUpdatePushTokenPost(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePushTokenSessionsUpdatePushTokenPostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>>
    
    export type UpdatePushTokenSessionsUpdatePushTokenPostMutationError = ErrorType<unknown>

    /**
 * @summary Update Push Token
 */
export const useUpdatePushTokenSessionsUpdatePushTokenPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, TError,{params: UpdatePushTokenSessionsUpdatePushTokenPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>,
        TError,
        {params: UpdatePushTokenSessionsUpdatePushTokenPostParams},
        TContext
      > => {
      return useMutation(getUpdatePushTokenSessionsUpdatePushTokenPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Ios Link
 */
export const getIosLinkAppsIosLinkGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<IOSLinkResponse>(
      {url: `/v1/auth/apps/ios-link`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIosLinkAppsIosLinkGetQueryKey = () => {
    return [
    `/v1/auth/apps/ios-link`
    ] as const;
    }

    
export const getGetIosLinkAppsIosLinkGetQueryOptions = <TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIosLinkAppsIosLinkGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>> = ({ signal }) => getIosLinkAppsIosLinkGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIosLinkAppsIosLinkGetQueryResult = NonNullable<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>>
export type GetIosLinkAppsIosLinkGetQueryError = ErrorType<unknown>


export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>,
          TError,
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>,
          TError,
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Ios Link
 */

export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIosLinkAppsIosLinkGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




