/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * call_service API
 * OpenAPI spec version: 1.0.0
 */
export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface CallActionMessageData {
  message?: string | null;
}

export interface CallActionResponse {
  status: string;
  data: CallActionMessageData;
}

export type CreateCallDataStatus = typeof CreateCallDataStatus[keyof typeof CreateCallDataStatus];


export const CreateCallDataStatus = {
  ringing: 'ringing',
  active: 'active',
  ended: 'ended',
  declined: 'declined',
  missed: 'missed',
} as const;

export interface CreateCallData {
  call_id: string;
  status: CreateCallDataStatus;
  started_at: string;
}

export interface CreateCallRequest {
  /** ID пользователя, которому звоним */
  to_user_id: string;
  /** Тип звонка */
  call_type?: 'audio';
}

export interface CreateCallResponse {
  status: string;
  data: CreateCallData;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface InternalAcceptCallRequest {
  user_id: string;
}

export type InternalCallStateDataStatus = typeof InternalCallStateDataStatus[keyof typeof InternalCallStateDataStatus];


export const InternalCallStateDataStatus = {
  ringing: 'ringing',
  active: 'active',
  ended: 'ended',
  declined: 'declined',
  missed: 'missed',
} as const;

export interface InternalCallStateData {
  call_id: string;
  status: InternalCallStateDataStatus;
  initiator_user_id: string;
  receiver_user_ids: string[];
  call_type: 'audio';
  started_at: string;
  answered_at: string | null;
  ended_at: string | null;
}

export interface InternalCallStateResponse {
  status: string;
  data: InternalCallStateData;
}

export interface InternalEndCallRequest {
  current_user: string;
  set_missed?: boolean;
}

