/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * achievement_service API
 * OpenAPI spec version: 1.0.0
 */
export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

/**
 * Тип медали
 */
export type PublicAchievementItemBadgeType = typeof PublicAchievementItemBadgeType[keyof typeof PublicAchievementItemBadgeType];


export const PublicAchievementItemBadgeType = {
  bronze: 'bronze',
  silver: 'silver',
  gold: 'gold',
  platinum: 'platinum',
  diamond: 'diamond',
  legendary: 'legendary',
} as const;

export interface PublicAchievementItem {
  /** ID ачивки (achievements.id) */
  achievement_id: number;
  /** Код ачивки */
  code: string;
  /** Название ачивки */
  name: string;
  /** Описание ачивки */
  description?: string | null;
  /** Путь к иконке */
  icon?: string | null;
  /** Категория (Posts, Comments, Profile, ...) */
  category?: string | null;
  /** Тип медали */
  badge_type: PublicAchievementItemBadgeType;
  /** Выполнена ли ачивка пользователем */
  is_completed: boolean;
  /** Когда пользователь получил ачивку */
  unlocked_at?: string | null;
  /** Текущий прогресс пользователя (None, если еще нет записи) */
  progress?: number | null;
  /** Необходимый прогресс для выполнения */
  required_progress?: number | null;
}

export type PublicAchievementListDataItems = {[key: string]: PublicAchievementItem[]};

export interface PublicAchievementListData {
  items: PublicAchievementListDataItems;
}

export interface InternalAchievementListResponse {
  status: string;
  data: PublicAchievementListData;
}

export interface InternalAchievementProgressUpdateData {
  /** ID ачивки (achievements.id) */
  achievement_id: number;
  /** Код ачивки */
  achievement_code: string;
  /** Текущий прогресс пользователя по ачивке */
  progress: number;
  /** Сколько нужно для выполнения ачивки */
  required_progress: number;
  /** Флаг: ачивка полностью выполнена */
  is_completed: boolean;
  /** Была ли ачивка разблокирована именно в этом вызове */
  just_unlocked: boolean;
  /** Когда ачивка была выполнена (если выполнена) */
  unlocked_at?: string | null;
}

export interface InternalAchievementProgressUpdateRequest {
  /** ID пользователя */
  user_id: string;
  /** Код ачивки (из achievements.code) */
  achievement_code: string;
  /**
   * Насколько увеличить прогресс (по умолчанию 1)
   * @exclusiveMinimum 0
   */
  increment?: number;
}

export interface InternalAchievementProgressUpdateResponse {
  status: string;
  data: InternalAchievementProgressUpdateData;
}

export interface InternalAchievementUpdateAllRequest {
  /** ID пользователя */
  user_id: string;
}

export interface PublicAchievementListResponse {
  status: string;
  data: PublicAchievementListData;
}

export type InternalAchievementListInternalListGetParams = {
/**
 * ID пользователя, для которого нужно получить список ачивок
 */
user_id: string;
/**
 * для своего профиля флаг
 */
for_self: boolean;
};

