/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  IOSLinkResponse
} from '../auth-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get Ios Link
 */
export const getIosLinkAppsIosLinkGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<IOSLinkResponse>(
      {url: `/v1/auth/apps/ios-link`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIosLinkAppsIosLinkGetQueryKey = () => {
    return [
    `/v1/auth/apps/ios-link`
    ] as const;
    }

    
export const getGetIosLinkAppsIosLinkGetQueryOptions = <TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIosLinkAppsIosLinkGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>> = ({ signal }) => getIosLinkAppsIosLinkGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIosLinkAppsIosLinkGetQueryResult = NonNullable<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>>
export type GetIosLinkAppsIosLinkGetQueryError = ErrorType<unknown>


export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>,
          TError,
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>,
          TError,
          Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Ios Link
 */

export function useGetIosLinkAppsIosLinkGet<TData = Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIosLinkAppsIosLinkGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIosLinkAppsIosLinkGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




