/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  ChangePasswordRequest
} from '../auth-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Изменение пароля текущего пользователя.

Требуется авторизация. Старый пароль должен быть указан верно.
Новый пароль должен отличаться от старого.
 * @summary Change Password
 */
export const changePasswordPasswordChangePost = (
    changePasswordRequest: BodyType<ChangePasswordRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/password/change`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordRequest, signal
    },
      options);
    }
  


export const getChangePasswordPasswordChangePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext> => {

const mutationKey = ['changePasswordPasswordChangePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, {data: BodyType<ChangePasswordRequest>}> = (props) => {
          const {data} = props ?? {};

          return  changePasswordPasswordChangePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordPasswordChangePostMutationResult = NonNullable<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>>
    export type ChangePasswordPasswordChangePostMutationBody = BodyType<ChangePasswordRequest>
    export type ChangePasswordPasswordChangePostMutationError = ErrorType<unknown>

    /**
 * @summary Change Password
 */
export const useChangePasswordPasswordChangePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordPasswordChangePost>>, TError,{data: BodyType<ChangePasswordRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePasswordPasswordChangePost>>,
        TError,
        {data: BodyType<ChangePasswordRequest>},
        TContext
      > => {
      return useMutation(getChangePasswordPasswordChangePostMutationOptions(options), queryClient);
    }
    /**
 * Запрос на сброс пароля (заглушка).

TODO: Реализовать сброс пароля через email/SMS.
 * @summary Request Password Reset
 */
export const requestPasswordResetPasswordResetPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/password/reset`, method: 'POST', signal
    },
      options);
    }
  


export const getRequestPasswordResetPasswordResetPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, TError,void, TContext> => {

const mutationKey = ['requestPasswordResetPasswordResetPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, void> = () => {
          

          return  requestPasswordResetPasswordResetPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RequestPasswordResetPasswordResetPostMutationResult = NonNullable<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>>
    
    export type RequestPasswordResetPasswordResetPostMutationError = ErrorType<unknown>

    /**
 * @summary Request Password Reset
 */
export const useRequestPasswordResetPasswordResetPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof requestPasswordResetPasswordResetPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRequestPasswordResetPasswordResetPostMutationOptions(options), queryClient);
    }
    /**
 * Подтверждение сброса пароля (заглушка).

TODO: Реализовать подтверждение сброса пароля.
 * @summary Confirm Password Reset
 */
export const confirmPasswordResetPasswordResetConfirmPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/password/reset/confirm`, method: 'POST', signal
    },
      options);
    }
  


export const getConfirmPasswordResetPasswordResetConfirmPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, TError,void, TContext> => {

const mutationKey = ['confirmPasswordResetPasswordResetConfirmPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, void> = () => {
          

          return  confirmPasswordResetPasswordResetConfirmPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmPasswordResetPasswordResetConfirmPostMutationResult = NonNullable<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>>
    
    export type ConfirmPasswordResetPasswordResetConfirmPostMutationError = ErrorType<unknown>

    /**
 * @summary Confirm Password Reset
 */
export const useConfirmPasswordResetPasswordResetConfirmPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmPasswordResetPasswordResetConfirmPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getConfirmPasswordResetPasswordResetConfirmPostMutationOptions(options), queryClient);
    }
    