/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * User API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseInfiniteQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  BlacklistCreateRequest,
  BlacklistCreateResponse,
  BlacklistDeleteRequest,
  BlacklistInfoResponse,
  ContactCountResponse,
  ContactCreateRequest,
  ContactCreateResponse,
  ContactDeleteRequest,
  ContactInfoResponse,
  ContactUpdateRequest,
  GetBlacklistBlacklistListGetParams,
  GetContactsContactListGetParams,
  GetUserRoleRoleGetParams,
  UserRoleResponse
} from '../user-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает количество контактов текущего пользователя.
 * @summary Get Contact Count
 */
export const getContactCountContactCountGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ContactCountResponse>(
      {url: `/v1/user/contact/count`, method: 'GET', signal
    },
      options);
    }
  



export const getGetContactCountContactCountGetQueryKey = () => {
    return [
    `/v1/user/contact/count`
    ] as const;
    }

    
export const getGetContactCountContactCountGetQueryOptions = <TData = Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactCountContactCountGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactCountContactCountGet>>> = ({ signal }) => getContactCountContactCountGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactCountContactCountGetQueryResult = NonNullable<Awaited<ReturnType<typeof getContactCountContactCountGet>>>
export type GetContactCountContactCountGetQueryError = ErrorType<unknown>


export function useGetContactCountContactCountGet<TData = Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactCountContactCountGet>>,
          TError,
          Awaited<ReturnType<typeof getContactCountContactCountGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactCountContactCountGet<TData = Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactCountContactCountGet>>,
          TError,
          Awaited<ReturnType<typeof getContactCountContactCountGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactCountContactCountGet<TData = Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Contact Count
 */

export function useGetContactCountContactCountGet<TData = Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactCountContactCountGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactCountContactCountGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Contacts
 */
export const getContactsContactListGet = (
    params?: GetContactsContactListGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ContactInfoResponse>(
      {url: `/v1/user/contact/list`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetContactsContactListGetQueryKey = (params?: GetContactsContactListGetParams,) => {
    return [
    `/v1/user/contact/list`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetContactsContactListGetInfiniteQueryKey = (params?: GetContactsContactListGetParams,) => {
    return [
    'infinite', `/v1/user/contact/list`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetContactsContactListGetQueryOptions = <TData = Awaited<ReturnType<typeof getContactsContactListGet>>, TError = ErrorType<unknown>>(params?: GetContactsContactListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactsContactListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactsContactListGet>>> = ({ signal }) => getContactsContactListGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactsContactListGetQueryResult = NonNullable<Awaited<ReturnType<typeof getContactsContactListGet>>>
export type GetContactsContactListGetQueryError = ErrorType<unknown>


export function useGetContactsContactListGet<TData = Awaited<ReturnType<typeof getContactsContactListGet>>, TError = ErrorType<unknown>>(
 params: undefined |  GetContactsContactListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsContactListGet>>,
          TError,
          Awaited<ReturnType<typeof getContactsContactListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactListGet<TData = Awaited<ReturnType<typeof getContactsContactListGet>>, TError = ErrorType<unknown>>(
 params?: GetContactsContactListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContactsContactListGet>>,
          TError,
          Awaited<ReturnType<typeof getContactsContactListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactListGet<TData = Awaited<ReturnType<typeof getContactsContactListGet>>, TError = ErrorType<unknown>>(
 params?: GetContactsContactListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Contacts
 */

export function useGetContactsContactListGet<TData = Awaited<ReturnType<typeof getContactsContactListGet>>, TError = ErrorType<unknown>>(
 params?: GetContactsContactListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactsContactListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetContactsContactListGetSuspenseInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getContactsContactListGet>>, GetContactsContactListGetParams['offset']>, TError = ErrorType<unknown>>(params?: GetContactsContactListGetParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData, QueryKey, GetContactsContactListGetParams['offset']>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContactsContactListGetInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContactsContactListGet>>, QueryKey, GetContactsContactListGetParams['offset']> = ({ signal, pageParam }) => getContactsContactListGet({...params, 'offset': pageParam || params?.['offset']}, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData, QueryKey, GetContactsContactListGetParams['offset']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetContactsContactListGetSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getContactsContactListGet>>>
export type GetContactsContactListGetSuspenseInfiniteQueryError = ErrorType<unknown>


export function useGetContactsContactListGetSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getContactsContactListGet>>, GetContactsContactListGetParams['offset']>, TError = ErrorType<unknown>>(
 params: undefined |  GetContactsContactListGetParams, options: { query:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData, QueryKey, GetContactsContactListGetParams['offset']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactListGetSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getContactsContactListGet>>, GetContactsContactListGetParams['offset']>, TError = ErrorType<unknown>>(
 params?: GetContactsContactListGetParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData, QueryKey, GetContactsContactListGetParams['offset']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetContactsContactListGetSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getContactsContactListGet>>, GetContactsContactListGetParams['offset']>, TError = ErrorType<unknown>>(
 params?: GetContactsContactListGetParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData, QueryKey, GetContactsContactListGetParams['offset']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Contacts
 */

export function useGetContactsContactListGetSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getContactsContactListGet>>, GetContactsContactListGetParams['offset']>, TError = ErrorType<unknown>>(
 params?: GetContactsContactListGetParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getContactsContactListGet>>, TError, TData, QueryKey, GetContactsContactListGetParams['offset']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetContactsContactListGetSuspenseInfiniteQueryOptions(params,options)

  const query = useSuspenseInfiniteQuery(queryOptions, queryClient) as  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Передать или user_id или login или friend_code
 * @summary Add Contact
 */
export const addContactContactAddPost = (
    contactCreateRequest: BodyType<ContactCreateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ContactCreateResponse>(
      {url: `/v1/user/contact/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: contactCreateRequest, signal
    },
      options);
    }
  


export const getAddContactContactAddPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContactContactAddPost>>, TError,{data: BodyType<ContactCreateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addContactContactAddPost>>, TError,{data: BodyType<ContactCreateRequest>}, TContext> => {

const mutationKey = ['addContactContactAddPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addContactContactAddPost>>, {data: BodyType<ContactCreateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  addContactContactAddPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddContactContactAddPostMutationResult = NonNullable<Awaited<ReturnType<typeof addContactContactAddPost>>>
    export type AddContactContactAddPostMutationBody = BodyType<ContactCreateRequest>
    export type AddContactContactAddPostMutationError = ErrorType<unknown>

    /**
 * @summary Add Contact
 */
export const useAddContactContactAddPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContactContactAddPost>>, TError,{data: BodyType<ContactCreateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addContactContactAddPost>>,
        TError,
        {data: BodyType<ContactCreateRequest>},
        TContext
      > => {
      return useMutation(getAddContactContactAddPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Contact
 */
export const updateContactContactUpdatePatch = (
    contactUpdateRequest: BodyType<ContactUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/user/contact/update`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: contactUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateContactContactUpdatePatchMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContactContactUpdatePatch>>, TError,{data: BodyType<ContactUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateContactContactUpdatePatch>>, TError,{data: BodyType<ContactUpdateRequest>}, TContext> => {

const mutationKey = ['updateContactContactUpdatePatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContactContactUpdatePatch>>, {data: BodyType<ContactUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  updateContactContactUpdatePatch(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateContactContactUpdatePatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateContactContactUpdatePatch>>>
    export type UpdateContactContactUpdatePatchMutationBody = BodyType<ContactUpdateRequest>
    export type UpdateContactContactUpdatePatchMutationError = ErrorType<unknown>

    /**
 * @summary Update Contact
 */
export const useUpdateContactContactUpdatePatch = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContactContactUpdatePatch>>, TError,{data: BodyType<ContactUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateContactContactUpdatePatch>>,
        TError,
        {data: BodyType<ContactUpdateRequest>},
        TContext
      > => {
      return useMutation(getUpdateContactContactUpdatePatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove Contact
 */
export const removeContactContactRemoveDelete = (
    contactDeleteRequest: BodyType<ContactDeleteRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/user/contact/remove`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: contactDeleteRequest, signal
    },
      options);
    }
  


export const getRemoveContactContactRemoveDeleteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeContactContactRemoveDelete>>, TError,{data: BodyType<ContactDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeContactContactRemoveDelete>>, TError,{data: BodyType<ContactDeleteRequest>}, TContext> => {

const mutationKey = ['removeContactContactRemoveDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeContactContactRemoveDelete>>, {data: BodyType<ContactDeleteRequest>}> = (props) => {
          const {data} = props ?? {};

          return  removeContactContactRemoveDelete(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveContactContactRemoveDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeContactContactRemoveDelete>>>
    export type RemoveContactContactRemoveDeleteMutationBody = BodyType<ContactDeleteRequest>
    export type RemoveContactContactRemoveDeleteMutationError = ErrorType<unknown>

    /**
 * @summary Remove Contact
 */
export const useRemoveContactContactRemoveDelete = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeContactContactRemoveDelete>>, TError,{data: BodyType<ContactDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeContactContactRemoveDelete>>,
        TError,
        {data: BodyType<ContactDeleteRequest>},
        TContext
      > => {
      return useMutation(getRemoveContactContactRemoveDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Blacklist
 */
export const getBlacklistBlacklistListGet = (
    params?: GetBlacklistBlacklistListGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BlacklistInfoResponse>(
      {url: `/v1/user/blacklist/list`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetBlacklistBlacklistListGetQueryKey = (params?: GetBlacklistBlacklistListGetParams,) => {
    return [
    `/v1/user/blacklist/list`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetBlacklistBlacklistListGetQueryOptions = <TData = Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError = ErrorType<unknown>>(params?: GetBlacklistBlacklistListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBlacklistBlacklistListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>> = ({ signal }) => getBlacklistBlacklistListGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBlacklistBlacklistListGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>>
export type GetBlacklistBlacklistListGetQueryError = ErrorType<unknown>


export function useGetBlacklistBlacklistListGet<TData = Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError = ErrorType<unknown>>(
 params: undefined |  GetBlacklistBlacklistListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>,
          TError,
          Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBlacklistBlacklistListGet<TData = Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError = ErrorType<unknown>>(
 params?: GetBlacklistBlacklistListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>,
          TError,
          Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBlacklistBlacklistListGet<TData = Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError = ErrorType<unknown>>(
 params?: GetBlacklistBlacklistListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Blacklist
 */

export function useGetBlacklistBlacklistListGet<TData = Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError = ErrorType<unknown>>(
 params?: GetBlacklistBlacklistListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBlacklistBlacklistListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBlacklistBlacklistListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Add To Blacklist
 */
export const addToBlacklistBlacklistAddPost = (
    blacklistCreateRequest: BodyType<BlacklistCreateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BlacklistCreateResponse>(
      {url: `/v1/user/blacklist/add`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: blacklistCreateRequest, signal
    },
      options);
    }
  


export const getAddToBlacklistBlacklistAddPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToBlacklistBlacklistAddPost>>, TError,{data: BodyType<BlacklistCreateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof addToBlacklistBlacklistAddPost>>, TError,{data: BodyType<BlacklistCreateRequest>}, TContext> => {

const mutationKey = ['addToBlacklistBlacklistAddPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addToBlacklistBlacklistAddPost>>, {data: BodyType<BlacklistCreateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  addToBlacklistBlacklistAddPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddToBlacklistBlacklistAddPostMutationResult = NonNullable<Awaited<ReturnType<typeof addToBlacklistBlacklistAddPost>>>
    export type AddToBlacklistBlacklistAddPostMutationBody = BodyType<BlacklistCreateRequest>
    export type AddToBlacklistBlacklistAddPostMutationError = ErrorType<unknown>

    /**
 * @summary Add To Blacklist
 */
export const useAddToBlacklistBlacklistAddPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addToBlacklistBlacklistAddPost>>, TError,{data: BodyType<BlacklistCreateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addToBlacklistBlacklistAddPost>>,
        TError,
        {data: BodyType<BlacklistCreateRequest>},
        TContext
      > => {
      return useMutation(getAddToBlacklistBlacklistAddPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove From Blacklist
 */
export const removeFromBlacklistBlacklistRemoveDelete = (
    blacklistDeleteRequest: BodyType<BlacklistDeleteRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/user/blacklist/remove`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: blacklistDeleteRequest, signal
    },
      options);
    }
  


export const getRemoveFromBlacklistBlacklistRemoveDeleteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromBlacklistBlacklistRemoveDelete>>, TError,{data: BodyType<BlacklistDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof removeFromBlacklistBlacklistRemoveDelete>>, TError,{data: BodyType<BlacklistDeleteRequest>}, TContext> => {

const mutationKey = ['removeFromBlacklistBlacklistRemoveDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeFromBlacklistBlacklistRemoveDelete>>, {data: BodyType<BlacklistDeleteRequest>}> = (props) => {
          const {data} = props ?? {};

          return  removeFromBlacklistBlacklistRemoveDelete(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveFromBlacklistBlacklistRemoveDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeFromBlacklistBlacklistRemoveDelete>>>
    export type RemoveFromBlacklistBlacklistRemoveDeleteMutationBody = BodyType<BlacklistDeleteRequest>
    export type RemoveFromBlacklistBlacklistRemoveDeleteMutationError = ErrorType<unknown>

    /**
 * @summary Remove From Blacklist
 */
export const useRemoveFromBlacklistBlacklistRemoveDelete = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeFromBlacklistBlacklistRemoveDelete>>, TError,{data: BodyType<BlacklistDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeFromBlacklistBlacklistRemoveDelete>>,
        TError,
        {data: BodyType<BlacklistDeleteRequest>},
        TContext
      > => {
      return useMutation(getRemoveFromBlacklistBlacklistRemoveDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get User Role
 */
export const getUserRoleRoleGet = (
    params?: GetUserRoleRoleGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserRoleResponse>(
      {url: `/v1/user/role`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetUserRoleRoleGetQueryKey = (params?: GetUserRoleRoleGetParams,) => {
    return [
    `/v1/user/role`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUserRoleRoleGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError = ErrorType<unknown>>(params?: GetUserRoleRoleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserRoleRoleGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserRoleRoleGet>>> = ({ signal }) => getUserRoleRoleGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserRoleRoleGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserRoleRoleGet>>>
export type GetUserRoleRoleGetQueryError = ErrorType<unknown>


export function useGetUserRoleRoleGet<TData = Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError = ErrorType<unknown>>(
 params: undefined |  GetUserRoleRoleGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRoleRoleGet>>,
          TError,
          Awaited<ReturnType<typeof getUserRoleRoleGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserRoleRoleGet<TData = Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError = ErrorType<unknown>>(
 params?: GetUserRoleRoleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserRoleRoleGet>>,
          TError,
          Awaited<ReturnType<typeof getUserRoleRoleGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserRoleRoleGet<TData = Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError = ErrorType<unknown>>(
 params?: GetUserRoleRoleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Role
 */

export function useGetUserRoleRoleGet<TData = Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError = ErrorType<unknown>>(
 params?: GetUserRoleRoleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserRoleRoleGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserRoleRoleGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




