/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  TokenRefreshRequest,
  TokenRefreshResponse
} from '../auth-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Обновление access/refresh токенов.

Для web-клиентов токены берутся из cookie.
Для API/mobile клиентов токены берутся из тела запроса.
 * @summary Refresh Token
 */
export const refreshTokenTokenRefreshPost = (
    tokenRefreshRequest: BodyType<TokenRefreshRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<TokenRefreshResponse>(
      {url: `/v1/auth/token/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tokenRefreshRequest, signal
    },
      options);
    }
  


export const getRefreshTokenTokenRefreshPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshTokenTokenRefreshPost>>, TError,{data: BodyType<TokenRefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshTokenTokenRefreshPost>>, TError,{data: BodyType<TokenRefreshRequest>}, TContext> => {

const mutationKey = ['refreshTokenTokenRefreshPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshTokenTokenRefreshPost>>, {data: BodyType<TokenRefreshRequest>}> = (props) => {
          const {data} = props ?? {};

          return  refreshTokenTokenRefreshPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenTokenRefreshPostMutationResult = NonNullable<Awaited<ReturnType<typeof refreshTokenTokenRefreshPost>>>
    export type RefreshTokenTokenRefreshPostMutationBody = BodyType<TokenRefreshRequest>
    export type RefreshTokenTokenRefreshPostMutationError = ErrorType<unknown>

    /**
 * @summary Refresh Token
 */
export const useRefreshTokenTokenRefreshPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshTokenTokenRefreshPost>>, TError,{data: BodyType<TokenRefreshRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshTokenTokenRefreshPost>>,
        TError,
        {data: BodyType<TokenRefreshRequest>},
        TContext
      > => {
      return useMutation(getRefreshTokenTokenRefreshPostMutationOptions(options), queryClient);
    }
    