/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * storage_service API
 * OpenAPI spec version: 1.0.0
 */
export interface AvatarBatchRequest {
  user_ids: string[];
}

export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface BodyUploadAvatarAvatarUploadPost {
  file: Blob;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface UploadAvatarData {
  /** file_id */
  file_id: string;
}

export interface UploadAvatarResponse {
  status: string;
  data: UploadAvatarData;
}

export type DownloadAvatarAvatarDownloadUserIdGetParams = {
file_id: string;
};

