/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * storage_service API
 * OpenAPI spec version: 1.0.0
 */
export interface AvatarBatchRequest {
  user_ids: string[];
}

export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface BodyUploadAvatarAvatarUploadPost {
  file: Blob;
}

export type MediaType = typeof MediaType[keyof typeof MediaType];


export const MediaType = {
  image: 'image',
  video: 'video',
  audio: 'audio',
  voice: 'voice',
} as const;

export interface BodyUploadFileFilesUploadPost {
  file: Blob;
  media_type: MediaType;
  no_compress?: boolean;
}

export interface FileAccessCheckRequest {
  /** File ID to check access for */
  file_id: string;
  /** User ID requesting access */
  user_id: string;
}

export interface FileAccessCheckResponse {
  /** Whether the user has access to the file */
  allowed: boolean;
}

export interface FileUploadData {
  /** Uploaded file ID */
  file_id: string;
}

export interface FileUploadResponse {
  status: string;
  data: FileUploadData;
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface UploadAvatarData {
  /** file_id */
  file_id: string;
}

export interface UploadAvatarResponse {
  status: string;
  data: UploadAvatarData;
}

export type DownloadAvatarAvatarDownloadUserIdGetParams = {
file_id: string;
version?: string;
};

