/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  InternalListSessionsInternalSessionsListGet200,
  InternalListSessionsInternalSessionsListGetParams,
  SessionsListResponse,
  UpdatePushTokenSessionsUpdatePushTokenPostParams
} from '../auth-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Возвращает список всех активных сессий текущего пользователя.
 * @summary List Sessions
 */
export const listSessionsSessionsListGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SessionsListResponse>(
      {url: `/v1/auth/sessions/list`, method: 'GET', signal
    },
      options);
    }
  



export const getListSessionsSessionsListGetQueryKey = () => {
    return [
    `/v1/auth/sessions/list`
    ] as const;
    }

    
export const getListSessionsSessionsListGetQueryOptions = <TData = Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSessionsSessionsListGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessionsSessionsListGet>>> = ({ signal }) => listSessionsSessionsListGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSessionsSessionsListGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSessionsSessionsListGet>>>
export type ListSessionsSessionsListGetQueryError = ErrorType<unknown>


export function useListSessionsSessionsListGet<TData = Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSessionsSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof listSessionsSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSessionsSessionsListGet<TData = Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSessionsSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof listSessionsSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSessionsSessionsListGet<TData = Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Sessions
 */

export function useListSessionsSessionsListGet<TData = Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSessionsSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSessionsSessionsListGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Деактивирует (отключает) конкретную сессию пользователя.

Текущая сессия должна существовать не менее SESSION_TRUST_DAYS дней.
Нельзя деактивировать текущую активную сессию.
 * @summary Revoke Session
 */
export const revokeSessionSessionsRevokeSessionIdPost = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/sessions/revoke/${sessionId}`, method: 'POST', signal
    },
      options);
    }
  


export const getRevokeSessionSessionsRevokeSessionIdPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, TError,{sessionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, TError,{sessionId: string}, TContext> => {

const mutationKey = ['revokeSessionSessionsRevokeSessionIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, {sessionId: string}> = (props) => {
          const {sessionId} = props ?? {};

          return  revokeSessionSessionsRevokeSessionIdPost(sessionId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeSessionSessionsRevokeSessionIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>>
    
    export type RevokeSessionSessionsRevokeSessionIdPostMutationError = ErrorType<unknown>

    /**
 * @summary Revoke Session
 */
export const useRevokeSessionSessionsRevokeSessionIdPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>, TError,{sessionId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeSessionSessionsRevokeSessionIdPost>>,
        TError,
        {sessionId: string},
        TContext
      > => {
      return useMutation(getRevokeSessionSessionsRevokeSessionIdPostMutationOptions(options), queryClient);
    }
    /**
 * Деактивирует все сессии пользователя, кроме текущей.

Текущая сессия должна существовать не менее SESSION_TRUST_DAYS дней.
 * @summary Revoke All Sessions Except Current
 */
export const revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/sessions/revoke_all_except_current`, method: 'POST', signal
    },
      options);
    }
  


export const getRevokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost>>, TError,void, TContext> => {

const mutationKey = ['revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost>>, void> = () => {
          

          return  revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RevokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPostMutationResult = NonNullable<Awaited<ReturnType<typeof revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost>>>
    
    export type RevokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPostMutationError = ErrorType<unknown>

    /**
 * @summary Revoke All Sessions Except Current
 */
export const useRevokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRevokeAllSessionsExceptCurrentSessionsRevokeAllExceptCurrentPostMutationOptions(options), queryClient);
    }
    /**
 * Обновляет FCM токен для текущей сессии.

Очищает этот токен в других активных сессиях пользователя.
 * @summary Update Push Token
 */
export const updatePushTokenSessionsUpdatePushTokenPost = (
    params: UpdatePushTokenSessionsUpdatePushTokenPostParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/sessions/update_push_token`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getUpdatePushTokenSessionsUpdatePushTokenPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, TError,{params: UpdatePushTokenSessionsUpdatePushTokenPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, TError,{params: UpdatePushTokenSessionsUpdatePushTokenPostParams}, TContext> => {

const mutationKey = ['updatePushTokenSessionsUpdatePushTokenPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, {params: UpdatePushTokenSessionsUpdatePushTokenPostParams}> = (props) => {
          const {params} = props ?? {};

          return  updatePushTokenSessionsUpdatePushTokenPost(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePushTokenSessionsUpdatePushTokenPostMutationResult = NonNullable<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>>
    
    export type UpdatePushTokenSessionsUpdatePushTokenPostMutationError = ErrorType<unknown>

    /**
 * @summary Update Push Token
 */
export const useUpdatePushTokenSessionsUpdatePushTokenPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>, TError,{params: UpdatePushTokenSessionsUpdatePushTokenPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePushTokenSessionsUpdatePushTokenPost>>,
        TError,
        {params: UpdatePushTokenSessionsUpdatePushTokenPostParams},
        TContext
      > => {
      return useMutation(getUpdatePushTokenSessionsUpdatePushTokenPostMutationOptions(options), queryClient);
    }
    /**
 * Деактивирует текущую сессию (выход из системы).

Очищает авторизационные куки.
 * @summary Session Logout
 */
export const sessionLogoutSessionsLogoutPost = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/sessions/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getSessionLogoutSessionsLogoutPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionLogoutSessionsLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sessionLogoutSessionsLogoutPost>>, TError,void, TContext> => {

const mutationKey = ['sessionLogoutSessionsLogoutPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sessionLogoutSessionsLogoutPost>>, void> = () => {
          

          return  sessionLogoutSessionsLogoutPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SessionLogoutSessionsLogoutPostMutationResult = NonNullable<Awaited<ReturnType<typeof sessionLogoutSessionsLogoutPost>>>
    
    export type SessionLogoutSessionsLogoutPostMutationError = ErrorType<unknown>

    /**
 * @summary Session Logout
 */
export const useSessionLogoutSessionsLogoutPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sessionLogoutSessionsLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sessionLogoutSessionsLogoutPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSessionLogoutSessionsLogoutPostMutationOptions(options), queryClient);
    }
    /**
 * Внутренний метод для получения списка сессий пользователя.
 * @summary Internal List Sessions
 */
export const internalListSessionsInternalSessionsListGet = (
    params: InternalListSessionsInternalSessionsListGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalListSessionsInternalSessionsListGet200>(
      {url: `/v1/auth/internal/sessions/list`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getInternalListSessionsInternalSessionsListGetQueryKey = (params?: InternalListSessionsInternalSessionsListGetParams,) => {
    return [
    `/v1/auth/internal/sessions/list`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getInternalListSessionsInternalSessionsListGetQueryOptions = <TData = Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError = ErrorType<unknown>>(params: InternalListSessionsInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalListSessionsInternalSessionsListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>> = ({ signal }) => internalListSessionsInternalSessionsListGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalListSessionsInternalSessionsListGetQueryResult = NonNullable<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>>
export type InternalListSessionsInternalSessionsListGetQueryError = ErrorType<unknown>


export function useInternalListSessionsInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalListSessionsInternalSessionsListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalListSessionsInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalListSessionsInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>,
          TError,
          Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalListSessionsInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalListSessionsInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Internal List Sessions
 */

export function useInternalListSessionsInternalSessionsListGet<TData = Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError = ErrorType<unknown>>(
 params: InternalListSessionsInternalSessionsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalListSessionsInternalSessionsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalListSessionsInternalSessionsListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




