/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Profile API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SearchByQueryUserSearchGetParams,
  UserSearchResponse
} from '../feed-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Поиск пользователей по логину (по префиксу, максимум 10 результатов).

Показываются пользователи:
- у которых is_searchable = true
- или находятся в контактах текущего пользователя
- или текущий пользователь находится у них в контактах
 * @summary Search By Query
 */
export const searchByQueryUserSearchGet = (
    params: SearchByQueryUserSearchGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserSearchResponse>(
      {url: `/v1/feed/user/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchByQueryUserSearchGetQueryKey = (params?: SearchByQueryUserSearchGetParams,) => {
    return [
    `/v1/feed/user/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchByQueryUserSearchGetQueryOptions = <TData = Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError = ErrorType<unknown>>(params: SearchByQueryUserSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchByQueryUserSearchGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>> = ({ signal }) => searchByQueryUserSearchGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchByQueryUserSearchGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>>
export type SearchByQueryUserSearchGetQueryError = ErrorType<unknown>


export function useSearchByQueryUserSearchGet<TData = Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQueryUserSearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByQueryUserSearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchByQueryUserSearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchByQueryUserSearchGet<TData = Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQueryUserSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByQueryUserSearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchByQueryUserSearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchByQueryUserSearchGet<TData = Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQueryUserSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search By Query
 */

export function useSearchByQueryUserSearchGet<TData = Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQueryUserSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQueryUserSearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchByQueryUserSearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




