/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as authenticationRouteRouteImport } from './routes/(authentication)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as authenticationProfileRouteImport } from './routes/(authentication)/profile'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationRouteRoute = authenticationRouteRouteImport.update({
  id: '/(authentication)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const authenticationProfileRoute = authenticationProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticationRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/profile': typeof authenticationProfileRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticationRouteRouteWithChildren
  '/profile': typeof authenticationProfileRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authentication)': typeof authenticationRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(authentication)/profile': typeof authenticationProfileRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/profile' | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/auth'
  id:
    | '__root__'
    | '/'
    | '/(authentication)'
    | '/auth'
    | '/(authentication)/profile'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticationRouteRoute: typeof authenticationRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)': {
      id: '/(authentication)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(authentication)/profile': {
      id: '/(authentication)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticationProfileRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
  }
}

interface authenticationRouteRouteChildren {
  authenticationProfileRoute: typeof authenticationProfileRoute
}

const authenticationRouteRouteChildren: authenticationRouteRouteChildren = {
  authenticationProfileRoute: authenticationProfileRoute,
}

const authenticationRouteRouteWithChildren =
  authenticationRouteRoute._addFileChildren(authenticationRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticationRouteRoute: authenticationRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
