/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizedRouteRouteImport } from './routes/_authorized/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizedSessionsRouteImport } from './routes/_authorized/sessions'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as AuthorizedYIndexRouteImport } from './routes/_authorized/y/index'
import { Route as AuthorizedYUUuidRouteImport } from './routes/_authorized/y/u/$uuid'

const AuthorizedRouteRoute = AuthorizedRouteRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedSessionsRoute = AuthorizedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthorizedYIndexRoute = AuthorizedYIndexRouteImport.update({
  id: '/y/',
  path: '/y/',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedYUUuidRoute = AuthorizedYUUuidRouteImport.update({
  id: '/y/u/$uuid',
  path: '/y/u/$uuid',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRoute
  '/sessions': typeof AuthorizedSessionsRoute
  '/y': typeof AuthorizedYIndexRoute
  '/y/u/$uuid': typeof AuthorizedYUUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRoute
  '/sessions': typeof AuthorizedSessionsRoute
  '/y': typeof AuthorizedYIndexRoute
  '/y/u/$uuid': typeof AuthorizedYUUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authorized': typeof AuthorizedRouteRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/_authorized/sessions': typeof AuthorizedSessionsRoute
  '/_authorized/y/': typeof AuthorizedYIndexRoute
  '/_authorized/y/u/$uuid': typeof AuthorizedYUUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/sessions' | '/y' | '/y/u/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/sessions' | '/y' | '/y/u/$uuid'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authorized'
    | '/_auth/auth'
    | '/_authorized/sessions'
    | '/_authorized/y/'
    | '/_authorized/y/u/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthorizedRouteRoute: typeof AuthorizedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized/sessions': {
      id: '/_authorized/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthorizedSessionsRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authorized/y/': {
      id: '/_authorized/y/'
      path: '/y'
      fullPath: '/y'
      preLoaderRoute: typeof AuthorizedYIndexRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/y/u/$uuid': {
      id: '/_authorized/y/u/$uuid'
      path: '/y/u/$uuid'
      fullPath: '/y/u/$uuid'
      preLoaderRoute: typeof AuthorizedYUUuidRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthorizedRouteRouteChildren {
  AuthorizedSessionsRoute: typeof AuthorizedSessionsRoute
  AuthorizedYIndexRoute: typeof AuthorizedYIndexRoute
  AuthorizedYUUuidRoute: typeof AuthorizedYUUuidRoute
}

const AuthorizedRouteRouteChildren: AuthorizedRouteRouteChildren = {
  AuthorizedSessionsRoute: AuthorizedSessionsRoute,
  AuthorizedYIndexRoute: AuthorizedYIndexRoute,
  AuthorizedYUUuidRoute: AuthorizedYUUuidRoute,
}

const AuthorizedRouteRouteWithChildren = AuthorizedRouteRoute._addFileChildren(
  AuthorizedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthorizedRouteRoute: AuthorizedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
