/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthorizedRouteRouteImport } from './routes/_authorized/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthorizedSessionsRouteImport } from './routes/_authorized/sessions'
import { Route as AuthorizedYIndexRouteImport } from './routes/_authorized/y/index'
import { Route as AuthorizedYUuidRouteImport } from './routes/_authorized/y/$uuid'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedRouteRoute = AuthorizedRouteRouteImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthorizedSessionsRoute = AuthorizedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedYIndexRoute = AuthorizedYIndexRouteImport.update({
  id: '/y/',
  path: '/y/',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)
const AuthorizedYUuidRoute = AuthorizedYUuidRouteImport.update({
  id: '/y/$uuid',
  path: '/y/$uuid',
  getParentRoute: () => AuthorizedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/sessions': typeof AuthorizedSessionsRoute
  '/auth/': typeof AuthIndexRoute
  '/y/$uuid': typeof AuthorizedYUuidRoute
  '/y': typeof AuthorizedYIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions': typeof AuthorizedSessionsRoute
  '/auth': typeof AuthIndexRoute
  '/y/$uuid': typeof AuthorizedYUuidRoute
  '/y': typeof AuthorizedYIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authorized': typeof AuthorizedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authorized/sessions': typeof AuthorizedSessionsRoute
  '/auth/': typeof AuthIndexRoute
  '/_authorized/y/$uuid': typeof AuthorizedYUuidRoute
  '/_authorized/y/': typeof AuthorizedYIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/sessions' | '/auth/' | '/y/$uuid' | '/y'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sessions' | '/auth' | '/y/$uuid' | '/y'
  id:
    | '__root__'
    | '/'
    | '/_authorized'
    | '/auth'
    | '/_authorized/sessions'
    | '/auth/'
    | '/_authorized/y/$uuid'
    | '/_authorized/y/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizedRouteRoute: typeof AuthorizedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authorized': {
      id: '/_authorized'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthorizedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authorized/sessions': {
      id: '/_authorized/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthorizedSessionsRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/y/': {
      id: '/_authorized/y/'
      path: '/y'
      fullPath: '/y'
      preLoaderRoute: typeof AuthorizedYIndexRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
    '/_authorized/y/$uuid': {
      id: '/_authorized/y/$uuid'
      path: '/y/$uuid'
      fullPath: '/y/$uuid'
      preLoaderRoute: typeof AuthorizedYUuidRouteImport
      parentRoute: typeof AuthorizedRouteRoute
    }
  }
}

interface AuthorizedRouteRouteChildren {
  AuthorizedSessionsRoute: typeof AuthorizedSessionsRoute
  AuthorizedYUuidRoute: typeof AuthorizedYUuidRoute
  AuthorizedYIndexRoute: typeof AuthorizedYIndexRoute
}

const AuthorizedRouteRouteChildren: AuthorizedRouteRouteChildren = {
  AuthorizedSessionsRoute: AuthorizedSessionsRoute,
  AuthorizedYUuidRoute: AuthorizedYUuidRoute,
  AuthorizedYIndexRoute: AuthorizedYIndexRoute,
}

const AuthorizedRouteRouteWithChildren = AuthorizedRouteRoute._addFileChildren(
  AuthorizedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizedRouteRoute: AuthorizedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
