/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as authenticationRouteRouteImport } from './routes/(authentication)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as authenticationProfileRouteImport } from './routes/(authentication)/profile'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationRouteRoute = authenticationRouteRouteImport.update({
  id: '/(authentication)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticationProfileRoute = authenticationProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticationRouteRouteWithChildren
  '/videos': typeof VideosRoute
  '/profile': typeof authenticationProfileRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticationRouteRouteWithChildren
  '/videos': typeof VideosRoute
  '/profile': typeof authenticationProfileRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authentication)': typeof authenticationRouteRouteWithChildren
  '/videos': typeof VideosRoute
  '/(authentication)/profile': typeof authenticationProfileRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/videos' | '/profile' | '/auth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/videos' | '/profile' | '/auth'
  id:
    | '__root__'
    | '/'
    | '/(authentication)'
    | '/videos'
    | '/(authentication)/profile'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticationRouteRoute: typeof authenticationRouteRouteWithChildren
  VideosRoute: typeof VideosRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)': {
      id: '/(authentication)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authentication)/profile': {
      id: '/(authentication)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticationProfileRouteImport
      parentRoute: typeof authenticationRouteRoute
    }
  }
}

interface authenticationRouteRouteChildren {
  authenticationProfileRoute: typeof authenticationProfileRoute
}

const authenticationRouteRouteChildren: authenticationRouteRouteChildren = {
  authenticationProfileRoute: authenticationProfileRoute,
}

const authenticationRouteRouteWithChildren =
  authenticationRouteRoute._addFileChildren(authenticationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticationRouteRoute: authenticationRouteRouteWithChildren,
  VideosRoute: VideosRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
