/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Profile API
 * OpenAPI spec version: 1.0.0
 */
export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface UserSearchResult {
  user_id: string;
  /** Модель как у /profile/{user_id} */
  profile?: unknown | null;
}

export interface ApiSchemasSearchSearchData {
  users: UserSearchResult[];
  groups?: unknown[];
  channels?: unknown[];
  messages?: unknown[];
}

export interface SearchResponse {
  status: string;
  data: ApiSchemasSearchSearchData;
}

export interface ApiSchemasUserSearchSearchData {
  users: UserSearchResult[];
}

export interface UserSearchResponse {
  status: string;
  data: ApiSchemasUserSearchSearchData;
}

export type SearchByQuerySearchGetParams = {
/**
 * @minLength 1
 */
query: string;
};

export type SearchByQueryUserSearchGetParams = {
/**
 * @minLength 1
 */
query: string;
};

