/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Profile API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SearchByQuerySearchGetParams,
  SearchResponse
} from '../feed-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Поиск пользователей по логину (по префиксу, максимум 10 результатов).

Показываются пользователи:
- у которых is_searchable = true
- или находятся в контактах текущего пользователя
- или текущий пользователь находится у них в контактах

Показываются беседы (не работает):
- в которых находится пользователь

Показываются паблики (не работает):
- у которых is_private = false
- или пользователь состоит в паблике
- или пользователь админ паблика

Показываются сообщения (не работает):
- в которых находится пользователь
 * @summary Search By Query
 */
export const searchByQuerySearchGet = (
    params: SearchByQuerySearchGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SearchResponse>(
      {url: `/v1/feed/search`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSearchByQuerySearchGetQueryKey = (params?: SearchByQuerySearchGetParams,) => {
    return [
    `/v1/feed/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getSearchByQuerySearchGetQueryOptions = <TData = Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError = ErrorType<unknown>>(params: SearchByQuerySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchByQuerySearchGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchByQuerySearchGet>>> = ({ signal }) => searchByQuerySearchGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchByQuerySearchGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchByQuerySearchGet>>>
export type SearchByQuerySearchGetQueryError = ErrorType<unknown>


export function useSearchByQuerySearchGet<TData = Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQuerySearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByQuerySearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchByQuerySearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchByQuerySearchGet<TData = Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQuerySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchByQuerySearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchByQuerySearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchByQuerySearchGet<TData = Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQuerySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search By Query
 */

export function useSearchByQuerySearchGet<TData = Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError = ErrorType<unknown>>(
 params: SearchByQuerySearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchByQuerySearchGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchByQuerySearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




