/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * call_service API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CallActionResponse,
  CreateCallRequest,
  CreateCallResponse,
  HTTPValidationError,
  InternalAcceptCallRequest,
  InternalCallStateResponse,
  InternalEndCallRequest
} from '../call-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Публичный метод — создать исходящий звонок.
 * @summary Create Call
 */
export const createCallCreatePost = (
    createCallRequest: BodyType<CreateCallRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateCallResponse>(
      {url: `/v1/call/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createCallRequest, signal
    },
      options);
    }
  


export const getCreateCallCreatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCallCreatePost>>, TError,{data: BodyType<CreateCallRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createCallCreatePost>>, TError,{data: BodyType<CreateCallRequest>}, TContext> => {

const mutationKey = ['createCallCreatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCallCreatePost>>, {data: BodyType<CreateCallRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createCallCreatePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCallCreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof createCallCreatePost>>>
    export type CreateCallCreatePostMutationBody = BodyType<CreateCallRequest>
    export type CreateCallCreatePostMutationError = ErrorType<unknown>

    /**
 * @summary Create Call
 */
export const useCreateCallCreatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCallCreatePost>>, TError,{data: BodyType<CreateCallRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCallCreatePost>>,
        TError,
        {data: BodyType<CreateCallRequest>},
        TContext
      > => {
      return useMutation(getCreateCallCreatePostMutationOptions(options), queryClient);
    }
    /**
 * Завершить активный звонок.
 * @summary End Call
 */
export const endCallCallIdEndPost = (
    callId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CallActionResponse>(
      {url: `/v1/call/${callId}/end`, method: 'POST', signal
    },
      options);
    }
  


export const getEndCallCallIdEndPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endCallCallIdEndPost>>, TError,{callId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof endCallCallIdEndPost>>, TError,{callId: string}, TContext> => {

const mutationKey = ['endCallCallIdEndPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof endCallCallIdEndPost>>, {callId: string}> = (props) => {
          const {callId} = props ?? {};

          return  endCallCallIdEndPost(callId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EndCallCallIdEndPostMutationResult = NonNullable<Awaited<ReturnType<typeof endCallCallIdEndPost>>>
    
    export type EndCallCallIdEndPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary End Call
 */
export const useEndCallCallIdEndPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof endCallCallIdEndPost>>, TError,{callId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof endCallCallIdEndPost>>,
        TError,
        {callId: string},
        TContext
      > => {
      return useMutation(getEndCallCallIdEndPostMutationOptions(options), queryClient);
    }
    /**
 * Завершить активный звонок.
 * @summary Internal End Call
 */
export const internalEndCallInternalCallIdEndPost = (
    callId: string,
    internalEndCallRequest: BodyType<InternalEndCallRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CallActionResponse>(
      {url: `/v1/call/internal/${callId}/end`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalEndCallRequest, signal
    },
      options);
    }
  


export const getInternalEndCallInternalCallIdEndPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalEndCallInternalCallIdEndPost>>, TError,{callId: string;data: BodyType<InternalEndCallRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof internalEndCallInternalCallIdEndPost>>, TError,{callId: string;data: BodyType<InternalEndCallRequest>}, TContext> => {

const mutationKey = ['internalEndCallInternalCallIdEndPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof internalEndCallInternalCallIdEndPost>>, {callId: string;data: BodyType<InternalEndCallRequest>}> = (props) => {
          const {callId,data} = props ?? {};

          return  internalEndCallInternalCallIdEndPost(callId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InternalEndCallInternalCallIdEndPostMutationResult = NonNullable<Awaited<ReturnType<typeof internalEndCallInternalCallIdEndPost>>>
    export type InternalEndCallInternalCallIdEndPostMutationBody = BodyType<InternalEndCallRequest>
    export type InternalEndCallInternalCallIdEndPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Internal End Call
 */
export const useInternalEndCallInternalCallIdEndPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalEndCallInternalCallIdEndPost>>, TError,{callId: string;data: BodyType<InternalEndCallRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof internalEndCallInternalCallIdEndPost>>,
        TError,
        {callId: string;data: BodyType<InternalEndCallRequest>},
        TContext
      > => {
      return useMutation(getInternalEndCallInternalCallIdEndPostMutationOptions(options), queryClient);
    }
    /**
 * Принять входящий звонок.
 * @summary Internal Accept Call
 */
export const internalAcceptCallInternalCallIdAcceptPost = (
    callId: string,
    internalAcceptCallRequest: BodyType<InternalAcceptCallRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CallActionResponse>(
      {url: `/v1/call/internal/${callId}/accept`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalAcceptCallRequest, signal
    },
      options);
    }
  


export const getInternalAcceptCallInternalCallIdAcceptPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalAcceptCallInternalCallIdAcceptPost>>, TError,{callId: string;data: BodyType<InternalAcceptCallRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof internalAcceptCallInternalCallIdAcceptPost>>, TError,{callId: string;data: BodyType<InternalAcceptCallRequest>}, TContext> => {

const mutationKey = ['internalAcceptCallInternalCallIdAcceptPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof internalAcceptCallInternalCallIdAcceptPost>>, {callId: string;data: BodyType<InternalAcceptCallRequest>}> = (props) => {
          const {callId,data} = props ?? {};

          return  internalAcceptCallInternalCallIdAcceptPost(callId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InternalAcceptCallInternalCallIdAcceptPostMutationResult = NonNullable<Awaited<ReturnType<typeof internalAcceptCallInternalCallIdAcceptPost>>>
    export type InternalAcceptCallInternalCallIdAcceptPostMutationBody = BodyType<InternalAcceptCallRequest>
    export type InternalAcceptCallInternalCallIdAcceptPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Internal Accept Call
 */
export const useInternalAcceptCallInternalCallIdAcceptPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalAcceptCallInternalCallIdAcceptPost>>, TError,{callId: string;data: BodyType<InternalAcceptCallRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof internalAcceptCallInternalCallIdAcceptPost>>,
        TError,
        {callId: string;data: BodyType<InternalAcceptCallRequest>},
        TContext
      > => {
      return useMutation(getInternalAcceptCallInternalCallIdAcceptPostMutationOptions(options), queryClient);
    }
    /**
 * Внутренний метод — получить состояние звонка.
 * @summary Internal Call State
 */
export const internalCallStateInternalCallIdGet = (
    callId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalCallStateResponse>(
      {url: `/v1/call/internal/${callId}`, method: 'GET', signal
    },
      options);
    }
  



export const getInternalCallStateInternalCallIdGetQueryKey = (callId: string,) => {
    return [
    `/v1/call/internal/${callId}`
    ] as const;
    }

    
export const getInternalCallStateInternalCallIdGetQueryOptions = <TData = Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError = ErrorType<HTTPValidationError>>(callId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalCallStateInternalCallIdGetQueryKey(callId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>> = ({ signal }) => internalCallStateInternalCallIdGet(callId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(callId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalCallStateInternalCallIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>>
export type InternalCallStateInternalCallIdGetQueryError = ErrorType<HTTPValidationError>


export function useInternalCallStateInternalCallIdGet<TData = Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError = ErrorType<HTTPValidationError>>(
 callId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>,
          TError,
          Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalCallStateInternalCallIdGet<TData = Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError = ErrorType<HTTPValidationError>>(
 callId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>,
          TError,
          Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalCallStateInternalCallIdGet<TData = Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError = ErrorType<HTTPValidationError>>(
 callId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Internal Call State
 */

export function useInternalCallStateInternalCallIdGet<TData = Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError = ErrorType<HTTPValidationError>>(
 callId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalCallStateInternalCallIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalCallStateInternalCallIdGetQueryOptions(callId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




