/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * storage_service API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AvatarBatchRequest,
  BodyUploadAvatarUploadAvatarPost,
  DownloadAvatarDownloadAvatarUserIdGetParams,
  HTTPValidationError,
  UploadAvatarResponse
} from '../storage-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Upload Avatar
 */
export const uploadAvatarUploadAvatarPost = (
    bodyUploadAvatarUploadAvatarPost: BodyType<BodyUploadAvatarUploadAvatarPost>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadAvatarUploadAvatarPost.file);

      return customInstance<UploadAvatarResponse>(
      {url: `/v1/storage/upload/avatar`, method: 'POST',
       data: formData, signal
    },
      options);
    }
  


export const getUploadAvatarUploadAvatarPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAvatarUploadAvatarPost>>, TError,{data: BodyType<BodyUploadAvatarUploadAvatarPost>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadAvatarUploadAvatarPost>>, TError,{data: BodyType<BodyUploadAvatarUploadAvatarPost>}, TContext> => {

const mutationKey = ['uploadAvatarUploadAvatarPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAvatarUploadAvatarPost>>, {data: BodyType<BodyUploadAvatarUploadAvatarPost>}> = (props) => {
          const {data} = props ?? {};

          return  uploadAvatarUploadAvatarPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadAvatarUploadAvatarPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAvatarUploadAvatarPost>>>
    export type UploadAvatarUploadAvatarPostMutationBody = BodyType<BodyUploadAvatarUploadAvatarPost>
    export type UploadAvatarUploadAvatarPostMutationError = ErrorType<unknown>

    /**
 * @summary Upload Avatar
 */
export const useUploadAvatarUploadAvatarPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAvatarUploadAvatarPost>>, TError,{data: BodyType<BodyUploadAvatarUploadAvatarPost>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAvatarUploadAvatarPost>>,
        TError,
        {data: BodyType<BodyUploadAvatarUploadAvatarPost>},
        TContext
      > => {
      return useMutation(getUploadAvatarUploadAvatarPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Download Avatar
 */
export const downloadAvatarDownloadAvatarUserIdGet = (
    userId: string,
    params: DownloadAvatarDownloadAvatarUserIdGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/storage/download/avatar/${userId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getDownloadAvatarDownloadAvatarUserIdGetQueryKey = (userId: string,
    params?: DownloadAvatarDownloadAvatarUserIdGetParams,) => {
    return [
    `/v1/storage/download/avatar/${userId}`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getDownloadAvatarDownloadAvatarUserIdGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError = ErrorType<HTTPValidationError>>(userId: string,
    params: DownloadAvatarDownloadAvatarUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadAvatarDownloadAvatarUserIdGetQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>> = ({ signal }) => downloadAvatarDownloadAvatarUserIdGet(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadAvatarDownloadAvatarUserIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>>
export type DownloadAvatarDownloadAvatarUserIdGetQueryError = ErrorType<HTTPValidationError>


export function useDownloadAvatarDownloadAvatarUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarDownloadAvatarUserIdGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAvatarDownloadAvatarUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarDownloadAvatarUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAvatarDownloadAvatarUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarDownloadAvatarUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Avatar
 */

export function useDownloadAvatarDownloadAvatarUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarDownloadAvatarUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarDownloadAvatarUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadAvatarDownloadAvatarUserIdGetQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Avatars Batch
 */
export const getAvatarsBatchInternalAvatarsListPost = (
    avatarBatchRequest: BodyType<AvatarBatchRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/storage/internal/avatars/list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: avatarBatchRequest, signal
    },
      options);
    }
  


export const getGetAvatarsBatchInternalAvatarsListPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, TError,{data: BodyType<AvatarBatchRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, TError,{data: BodyType<AvatarBatchRequest>}, TContext> => {

const mutationKey = ['getAvatarsBatchInternalAvatarsListPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, {data: BodyType<AvatarBatchRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getAvatarsBatchInternalAvatarsListPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetAvatarsBatchInternalAvatarsListPostMutationResult = NonNullable<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>>
    export type GetAvatarsBatchInternalAvatarsListPostMutationBody = BodyType<AvatarBatchRequest>
    export type GetAvatarsBatchInternalAvatarsListPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Get Avatars Batch
 */
export const useGetAvatarsBatchInternalAvatarsListPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, TError,{data: BodyType<AvatarBatchRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>,
        TError,
        {data: BodyType<AvatarBatchRequest>},
        TContext
      > => {
      return useMutation(getGetAvatarsBatchInternalAvatarsListPostMutationOptions(options), queryClient);
    }
    