/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * storage_service API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AvatarBatchRequest,
  BodyUploadAvatarAvatarUploadPost,
  DownloadAvatarAvatarDownloadUserIdGetParams,
  HTTPValidationError,
  UploadAvatarResponse
} from '../storage-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Upload Avatar
 */
export const uploadAvatarAvatarUploadPost = (
    bodyUploadAvatarAvatarUploadPost: BodyType<BodyUploadAvatarAvatarUploadPost>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadAvatarAvatarUploadPost.file);

      return customInstance<UploadAvatarResponse>(
      {url: `/v1/storage/avatar/upload`, method: 'POST',
       data: formData, signal
    },
      options);
    }
  


export const getUploadAvatarAvatarUploadPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAvatarAvatarUploadPost>>, TError,{data: BodyType<BodyUploadAvatarAvatarUploadPost>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadAvatarAvatarUploadPost>>, TError,{data: BodyType<BodyUploadAvatarAvatarUploadPost>}, TContext> => {

const mutationKey = ['uploadAvatarAvatarUploadPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAvatarAvatarUploadPost>>, {data: BodyType<BodyUploadAvatarAvatarUploadPost>}> = (props) => {
          const {data} = props ?? {};

          return  uploadAvatarAvatarUploadPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadAvatarAvatarUploadPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAvatarAvatarUploadPost>>>
    export type UploadAvatarAvatarUploadPostMutationBody = BodyType<BodyUploadAvatarAvatarUploadPost>
    export type UploadAvatarAvatarUploadPostMutationError = ErrorType<unknown>

    /**
 * @summary Upload Avatar
 */
export const useUploadAvatarAvatarUploadPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAvatarAvatarUploadPost>>, TError,{data: BodyType<BodyUploadAvatarAvatarUploadPost>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAvatarAvatarUploadPost>>,
        TError,
        {data: BodyType<BodyUploadAvatarAvatarUploadPost>},
        TContext
      > => {
      return useMutation(getUploadAvatarAvatarUploadPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Download Avatar
 */
export const downloadAvatarAvatarDownloadUserIdGet = (
    userId: string,
    params: DownloadAvatarAvatarDownloadUserIdGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/storage/avatar/download/${userId}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getDownloadAvatarAvatarDownloadUserIdGetQueryKey = (userId: string,
    params?: DownloadAvatarAvatarDownloadUserIdGetParams,) => {
    return [
    `/v1/storage/avatar/download/${userId}`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getDownloadAvatarAvatarDownloadUserIdGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError = ErrorType<HTTPValidationError>>(userId: string,
    params: DownloadAvatarAvatarDownloadUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadAvatarAvatarDownloadUserIdGetQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>> = ({ signal }) => downloadAvatarAvatarDownloadUserIdGet(userId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadAvatarAvatarDownloadUserIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>>
export type DownloadAvatarAvatarDownloadUserIdGetQueryError = ErrorType<HTTPValidationError>


export function useDownloadAvatarAvatarDownloadUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarAvatarDownloadUserIdGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAvatarAvatarDownloadUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarAvatarDownloadUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAvatarAvatarDownloadUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarAvatarDownloadUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Avatar
 */

export function useDownloadAvatarAvatarDownloadUserIdGet<TData = Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError = ErrorType<HTTPValidationError>>(
 userId: string,
    params: DownloadAvatarAvatarDownloadUserIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAvatarAvatarDownloadUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadAvatarAvatarDownloadUserIdGetQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Avatars Batch
 */
export const getAvatarsBatchInternalAvatarsListPost = (
    avatarBatchRequest: BodyType<AvatarBatchRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/v1/storage/internal/avatars/list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: avatarBatchRequest, signal
    },
      options);
    }
  


export const getGetAvatarsBatchInternalAvatarsListPostMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, TError,{data: BodyType<AvatarBatchRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, TError,{data: BodyType<AvatarBatchRequest>}, TContext> => {

const mutationKey = ['getAvatarsBatchInternalAvatarsListPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, {data: BodyType<AvatarBatchRequest>}> = (props) => {
          const {data} = props ?? {};

          return  getAvatarsBatchInternalAvatarsListPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetAvatarsBatchInternalAvatarsListPostMutationResult = NonNullable<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>>
    export type GetAvatarsBatchInternalAvatarsListPostMutationBody = BodyType<AvatarBatchRequest>
    export type GetAvatarsBatchInternalAvatarsListPostMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Get Avatars Batch
 */
export const useGetAvatarsBatchInternalAvatarsListPost = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>, TError,{data: BodyType<AvatarBatchRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getAvatarsBatchInternalAvatarsListPost>>,
        TError,
        {data: BodyType<AvatarBatchRequest>},
        TContext
      > => {
      return useMutation(getGetAvatarsBatchInternalAvatarsListPostMutationOptions(options), queryClient);
    }
    