/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * chat_private_service_python API
 * OpenAPI spec version: 1.0.0
 */
export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface InternalPrivateChatMembersData {
  is_exist: boolean;
  members: string[];
}

export interface InternalPrivateChatMembersResponse {
  status?: string;
  data: InternalPrivateChatMembersData;
}

/**
 * Системный отправитель (yobble, support, feedback, yobble_system)
 */
export type InternalPrivateMessageSendRequestSender = typeof InternalPrivateMessageSendRequestSender[keyof typeof InternalPrivateMessageSendRequestSender];


export const InternalPrivateMessageSendRequestSender = {
  yobble: 'yobble',
  support: 'support',
  feedback: 'feedback',
  yobble_system: 'yobble_system',
  feedback_idea: 'feedback_idea',
  feedback_issue: 'feedback_issue',
  feedback_praise: 'feedback_praise',
  feedback_content: 'feedback_content',
} as const;

export interface InternalPrivateMessageSendRequest {
  /** Системный отправитель (yobble, support, feedback, yobble_system) */
  sender: InternalPrivateMessageSendRequestSender;
  user_id: string;
  /** Содержимое сообщения (макс. 4096 символов) */
  content?: string | null;
  /** Содержимое сообщения для брокера (макс. 4096 символов) */
  broker_customization_msg?: string | null;
}

export interface MessageForward {
  /** Тип пересылаемого контента */
  forward_type?: 'chat_private_messages' | 'chat_group_messages' | 'chat_public_messages' | 'reply' | null;
  /** ID чата, откуда переслано сообщение */
  forward_sender_id?: string | null;
  /** Данные внутренний ид сообщения в forward_chat */
  forward_message_id?: number | null;
  /** Данные о чате пересылаемом (беседы и паблики) */
  forward_chat_data?: unknown | null;
}

export type MessageItemMessageTypeItem = typeof MessageItemMessageTypeItem[keyof typeof MessageItemMessageTypeItem];


export const MessageItemMessageTypeItem = {
  text: 'text',
  media: 'media',
  circle: 'circle',
  voice: 'voice',
  system: 'system',
  forward: 'forward',
  reply: 'reply',
  poll: 'poll',
} as const;

export interface MessageItem {
  /** внутренний ID сообщения */
  message_id: number;
  /** Типы сообщения */
  message_type: MessageItemMessageTypeItem[];
  forward_metadata: MessageForward | null;
  /** Чат ID */
  chat_id: string;
  /** Кто отправил */
  sender_id: string;
  /** Данные о пользователе */
  sender_data?: unknown | null;
  /** Текст сообщения */
  content?: string | null;
  /** Ссылка на медиа (заглушка) */
  media_link?: unknown | null;
  /** Флаг просмотра */
  is_viewed: boolean;
  /** Дата и время просмотра сообщения */
  viewed_at?: string | null;
  /** Дата и время создания сообщения */
  created_at: string;
  /** Было ли сообщение отредактировано */
  is_edited?: boolean;
  /** Дата и время обновления сообщения */
  updated_at?: string | null;
}

/**
 * Тип чата: self — чат с собой, private — приватный чат с другим пользователем
 */
export type PrivateChatCreateDataChatType = typeof PrivateChatCreateDataChatType[keyof typeof PrivateChatCreateDataChatType];


export const PrivateChatCreateDataChatType = {
  private: 'private',
  self: 'self',
} as const;

export interface PrivateChatCreateData {
  /** ID созданного или существующего приватного чата */
  chat_id: string;
  /** Тип чата: self — чат с собой, private — приватный чат с другим пользователем */
  chat_type: PrivateChatCreateDataChatType;
  /** Статус создания ('fine' или 'exists') */
  status: string;
  /** Сообщение */
  message: string;
}

export interface PrivateChatCreateResponse {
  status: string;
  data: PrivateChatCreateData;
}

export interface PrivateChatDeleteRequest {
  /** ID приватного чата */
  chat_id: string;
}

export interface PrivateChatHistoryData {
  items: MessageItem[];
  has_more: boolean;
}

export interface PrivateChatHistoryResponse {
  status: string;
  data: PrivateChatHistoryData;
}

/**
 * Тип чата
 */
export type PrivateChatListItemChatType = typeof PrivateChatListItemChatType[keyof typeof PrivateChatListItemChatType];


export const PrivateChatListItemChatType = {
  self: 'self',
  private: 'private',
} as const;

/**
 * Данные о чате
 */
export type PrivateChatListItemChatData = { [key: string]: unknown } | null;

export interface PrivateChatListItem {
  /** ID чата */
  chat_id: string;
  /** Тип чата */
  chat_type: PrivateChatListItemChatType;
  /** ID участников чата */
  chat_companion_ids?: string[];
  /** Данные о чате */
  chat_data?: PrivateChatListItemChatData;
  /** Последнее сообщение в чате */
  last_message?: MessageItem | null;
  /** Дата создания чата */
  created_at: string;
  /** Кол-во непрочитанных сообщений */
  unread_count: number;
}

export interface PrivateChatListData {
  items: PrivateChatListItem[];
  has_more: boolean;
}

export interface PrivateChatListResponse {
  status: string;
  data: PrivateChatListData;
}

export interface PrivateChatMarkReadData {
  /** ID чата */
  chat_id: string;
  /** Количество отмеченных сообщений */
  marked_count: number;
}

export interface PrivateChatMarkReadRequest {
  /** ID приватного чата */
  chat_id: string;
  /** ID сообщения для отметки (если None - все непрочитанные до последнего) */
  message_id?: number | null;
  /** Отметить все непрочитанные сообщения в чате */
  mark_all?: boolean;
}

export interface PrivateChatMarkReadResponse {
  status?: string;
  data: PrivateChatMarkReadData;
}

export interface PrivateMessageDeleteData {
  /** ID удалённого сообщения */
  message_id: number;
  /** ID чата */
  chat_id: string;
  /** Дата и время удаления */
  deleted_at: string;
  /** Удалено у всех или только у себя */
  delete_for_all: boolean;
}

export interface PrivateMessageDeleteRequest {
  /** ID приватного чата */
  chat_id: string;
  /** ID сообщения для удаления */
  message_id: number;
  /** Удалить у всех или только у себя */
  delete_for_all?: boolean;
}

export interface PrivateMessageDeleteResponse {
  status?: string;
  data: PrivateMessageDeleteData;
}

export interface PrivateMessageEditData {
  /** ID отредактированного сообщения */
  message_id: number;
  /** ID чата */
  chat_id: string;
  /** Новый текст сообщения */
  content: string;
  /** Дата и время редактирования */
  updated_at: string;
}

export interface PrivateMessageEditRequest {
  /** ID приватного чата */
  chat_id: string;
  /** ID сообщения для редактирования */
  message_id: number;
  /**
   * Новый текст сообщения
   * @maxLength 4096
   */
  content: string;
}

export interface PrivateMessageEditResponse {
  status?: string;
  data: PrivateMessageEditData;
}

export interface PrivateMessageSendData {
  message_id: number;
  chat_id: string;
  created_at: string;
}

export interface PrivateMessageSendRequest {
  chat_id: string;
  /** Содержимое сообщения (макс. 4096 символов) */
  content?: string | null;
  /** Один или несколько типов сообщения */
  message_type: 'text'[];
}

export interface PrivateMessageSendResponse {
  status: string;
  data: PrivateMessageSendData;
}

export type GetListPrivateChatsListGetParams = {
/**
 * Смещение для пагинации
 * @minimum 0
 */
offset?: number;
/**
 * Количество чатов для загрузки
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type GetPrivateChatHistoryHistoryGetParams = {
/**
 * ID приватного чата
 */
chat_id: string;
/**
 * Пагинация: внутренний ID последнего сообщения
 */
before_message_id?: number | null;
/**
 * Сколько сообщений загрузить (макс. 100)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * TODO (не работает) Загрузка истории чата при нажатии на forward
 */
is_forward?: boolean;
};

export type CreatePrivateChatByUuidCreatePostParams = {
target_user_id: string;
};

export type InternalMembersPrivateChatInternalMembersGetParams = {
chat_id: string;
};

