/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface BotListItem {
  id: string;
  login: string;
  created_at: string;
}

export interface BotListData {
  items: BotListItem[];
  has_more: boolean;
}

export interface BotListResponse {
  status: string;
  data: BotListData;
}

export interface ChangePasswordRequest {
  /** @maxLength 128 */
  old_password: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  new_password: string;
}

export interface IOSLinkData {
  link: string;
}

export interface IOSLinkResponse {
  status: string;
  data: IOSLinkData;
}

export interface LoginCodeRequest {
  login: string;
}

export interface LoginData {
  access_token: string;
  refresh_token: string;
  user_id: string;
}

export interface LoginRequest {
  login: string;
  password: string;
}

export interface LoginResponse {
  status?: string;
  data: LoginData;
}

export interface UserSessionItem {
  /** UUID сессии */
  id: string;
  /** IP-адрес клиента */
  ip_address?: string | null;
  /** User-Agent клиента */
  user_agent?: string | null;
  /** Тип клиента (web, mobile, bot и т.п.) */
  client_type: string;
  /** Активна ли сессия */
  is_active: boolean;
  /** Дата создания сессии */
  created_at: string;
  /** Последнее обновление токена */
  last_refresh_at: string;
  /** Текущая ли это сессия */
  is_current: boolean;
}

export interface SessionsListData {
  sessions: UserSessionItem[];
}

export interface SessionsListResponse {
  status?: string;
  data: SessionsListData;
}

export interface TokenData {
  access_token: string;
  refresh_token: string;
}

export interface TokenRefreshRequest {
  access_token?: string | null;
  refresh_token?: string | null;
}

export interface TokenRefreshResponse {
  status?: string;
  data: TokenData;
}

export interface VerifyCodeRequest {
  login: string;
  /**
   * @minLength 4
   * @maxLength 8
   */
  otp: string;
}

export interface ApiSchemasBotRegisterData {
  message: string;
  bot_id: string;
  token: string;
}

export interface ApiSchemasBotRegisterRequest {
  login: string;
}

export interface ApiSchemasBotRegisterResponse {
  status: string;
  data: ApiSchemasBotRegisterData;
}

export interface ApiSchemasRegisterRegisterData {
  message: string;
  user_id: string;
}

export interface ApiSchemasRegisterRegisterRequest {
  login: string;
  password: string;
  invite?: string | null;
}

export interface ApiSchemasRegisterRegisterResponse {
  status: string;
  data: ApiSchemasRegisterRegisterData;
}

export type GetUserBotsBotListGetParams = {
/**
 * Смещение для пагинации
 * @minimum 0
 */
offset?: number;
/**
 * Количество ботов для загрузки
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};

export type InternalSessionsListInternalSessionsListGetParams = {
target_user: string;
};

export type UpdatePushTokenSessionsUpdatePushTokenPostParams = {
fcm_token: string;
};

