/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface ChangePasswordRequest {
  /**
   * @minLength 6
   * @maxLength 128
   */
  old_password: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  new_password: string;
}

export interface IOSLinkData {
  link: string;
}

export interface IOSLinkResponse {
  status: string;
  data: IOSLinkData;
}

export interface LoginCodeRequest {
  login: string;
}

export interface LoginData {
  access_token: string;
  refresh_token: string;
  user_id: string;
}

export interface LoginRequest {
  login: string;
  password: string;
}

export interface LoginResponse {
  status?: string;
  data: LoginData;
}

export interface RegisterData {
  message: string;
  user_id: string;
}

export interface RegisterRequest {
  login: string;
  password: string;
  invite?: string | null;
}

export interface RegisterResponse {
  status: string;
  data: RegisterData;
}

export interface UserSessionItem {
  /** UUID сессии */
  id: string;
  /** IP-адрес клиента */
  ip_address?: string | null;
  /** User-Agent клиента */
  user_agent?: string | null;
  /** Тип клиента (web, mobile, bot и т.п.) */
  client_type: string;
  /** Активна ли сессия */
  is_active: boolean;
  /** Дата создания сессии */
  created_at: string;
  /** Последнее обновление токена */
  last_refresh_at: string;
  /** Текущая ли это сессия */
  is_current: boolean;
}

export interface SessionsListData {
  sessions: UserSessionItem[];
}

export interface SessionsListResponse {
  status?: string;
  data: SessionsListData;
}

export interface TokenData {
  access_token: string;
  refresh_token: string;
}

export interface TokenRefreshRequest {
  access_token?: string | null;
  refresh_token?: string | null;
}

export interface TokenRefreshResponse {
  status?: string;
  data: TokenData;
}

export interface VerifyCodeRequest {
  login: string;
  /**
   * @minLength 4
   * @maxLength 8
   */
  otp: string;
}

export type UpdatePushTokenSessionsUpdatePushTokenPostParams = {
/**
 * FCM токен для push уведомлений
 */
fcm_token: string;
};

export type InternalListSessionsInternalSessionsListGetParams = {
/**
 * ID пользователя
 */
target_user: string;
};

export type InternalListSessionsInternalSessionsListGet200 = { [key: string]: unknown };

