/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * chat_private_service_python API
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  CreatePrivateChatByUuidCreatePostParams,
  GetListPrivateChatsListGetParams,
  GetPrivateChatHistoryHistoryGetParams,
  InternalMembersPrivateChatInternalMembersGetParams,
  InternalPrivateChatMembersResponse,
  InternalPrivateMessageSendRequest,
  PrivateChatCreateResponse,
  PrivateChatDeleteRequest,
  PrivateChatHistoryResponse,
  PrivateChatListResponse,
  PrivateChatMarkReadRequest,
  PrivateChatMarkReadResponse,
  PrivateMessageDeleteRequest,
  PrivateMessageDeleteResponse,
  PrivateMessageEditRequest,
  PrivateMessageEditResponse,
  PrivateMessageSendRequest,
  PrivateMessageSendResponse
} from '../chat-private-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Delete Private Chat
 */
export const deletePrivateChatDeleteDelete = (
    privateChatDeleteRequest: BodyType<PrivateChatDeleteRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/chat/private/delete`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: privateChatDeleteRequest, signal
    },
      options);
    }
  


export const getDeletePrivateChatDeleteDeleteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrivateChatDeleteDelete>>, TError,{data: BodyType<PrivateChatDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePrivateChatDeleteDelete>>, TError,{data: BodyType<PrivateChatDeleteRequest>}, TContext> => {

const mutationKey = ['deletePrivateChatDeleteDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePrivateChatDeleteDelete>>, {data: BodyType<PrivateChatDeleteRequest>}> = (props) => {
          const {data} = props ?? {};

          return  deletePrivateChatDeleteDelete(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePrivateChatDeleteDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deletePrivateChatDeleteDelete>>>
    export type DeletePrivateChatDeleteDeleteMutationBody = BodyType<PrivateChatDeleteRequest>
    export type DeletePrivateChatDeleteDeleteMutationError = ErrorType<unknown>

    /**
 * @summary Delete Private Chat
 */
export const useDeletePrivateChatDeleteDelete = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrivateChatDeleteDelete>>, TError,{data: BodyType<PrivateChatDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePrivateChatDeleteDelete>>,
        TError,
        {data: BodyType<PrivateChatDeleteRequest>},
        TContext
      > => {
      return useMutation(getDeletePrivateChatDeleteDeleteMutationOptions(options), queryClient);
    }
    /**
 * @summary Get List Private Chats
 */
export const getListPrivateChatsListGet = (
    params?: GetListPrivateChatsListGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateChatListResponse>(
      {url: `/v1/chat/private/list`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetListPrivateChatsListGetQueryKey = (params?: GetListPrivateChatsListGetParams,) => {
    return [
    `/v1/chat/private/list`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetListPrivateChatsListGetQueryOptions = <TData = Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError = ErrorType<unknown>>(params?: GetListPrivateChatsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListPrivateChatsListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListPrivateChatsListGet>>> = ({ signal }) => getListPrivateChatsListGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListPrivateChatsListGetQueryResult = NonNullable<Awaited<ReturnType<typeof getListPrivateChatsListGet>>>
export type GetListPrivateChatsListGetQueryError = ErrorType<unknown>


export function useGetListPrivateChatsListGet<TData = Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError = ErrorType<unknown>>(
 params: undefined |  GetListPrivateChatsListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListPrivateChatsListGet>>,
          TError,
          Awaited<ReturnType<typeof getListPrivateChatsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListPrivateChatsListGet<TData = Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError = ErrorType<unknown>>(
 params?: GetListPrivateChatsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListPrivateChatsListGet>>,
          TError,
          Awaited<ReturnType<typeof getListPrivateChatsListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListPrivateChatsListGet<TData = Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError = ErrorType<unknown>>(
 params?: GetListPrivateChatsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get List Private Chats
 */

export function useGetListPrivateChatsListGet<TData = Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError = ErrorType<unknown>>(
 params?: GetListPrivateChatsListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListPrivateChatsListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListPrivateChatsListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Private Chat History
 */
export const getPrivateChatHistoryHistoryGet = (
    params: GetPrivateChatHistoryHistoryGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateChatHistoryResponse>(
      {url: `/v1/chat/private/history`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetPrivateChatHistoryHistoryGetInfiniteQueryKey = (params?: GetPrivateChatHistoryHistoryGetParams,) => {
    return [
    'infinite', `/v1/chat/private/history`, ...(params ? [params] : [])
    ] as const;
    }

export const getGetPrivateChatHistoryHistoryGetQueryKey = (params?: GetPrivateChatHistoryHistoryGetParams,) => {
    return [
    `/v1/chat/private/history`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetPrivateChatHistoryHistoryGetInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, GetPrivateChatHistoryHistoryGetParams['before_message_id']>, TError = ErrorType<unknown>>(params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData, QueryKey, GetPrivateChatHistoryHistoryGetParams['before_message_id']>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrivateChatHistoryHistoryGetInfiniteQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, QueryKey, GetPrivateChatHistoryHistoryGetParams['before_message_id']> = ({ signal, pageParam }) => getPrivateChatHistoryHistoryGet({...params, 'before_message_id': pageParam || params?.['before_message_id']}, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData, QueryKey, GetPrivateChatHistoryHistoryGetParams['before_message_id']> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPrivateChatHistoryHistoryGetInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>>
export type GetPrivateChatHistoryHistoryGetInfiniteQueryError = ErrorType<unknown>


export function useGetPrivateChatHistoryHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, GetPrivateChatHistoryHistoryGetParams['before_message_id']>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData, QueryKey, GetPrivateChatHistoryHistoryGetParams['before_message_id']>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrivateChatHistoryHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, GetPrivateChatHistoryHistoryGetParams['before_message_id']>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData, QueryKey, GetPrivateChatHistoryHistoryGetParams['before_message_id']>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, QueryKey
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrivateChatHistoryHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, GetPrivateChatHistoryHistoryGetParams['before_message_id']>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData, QueryKey, GetPrivateChatHistoryHistoryGetParams['before_message_id']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Private Chat History
 */

export function useGetPrivateChatHistoryHistoryGetInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, GetPrivateChatHistoryHistoryGetParams['before_message_id']>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData, QueryKey, GetPrivateChatHistoryHistoryGetParams['before_message_id']>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPrivateChatHistoryHistoryGetInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetPrivateChatHistoryHistoryGetQueryOptions = <TData = Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError = ErrorType<unknown>>(params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrivateChatHistoryHistoryGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>> = ({ signal }) => getPrivateChatHistoryHistoryGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPrivateChatHistoryHistoryGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>>
export type GetPrivateChatHistoryHistoryGetQueryError = ErrorType<unknown>


export function useGetPrivateChatHistoryHistoryGet<TData = Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrivateChatHistoryHistoryGet<TData = Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>,
          TError,
          Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrivateChatHistoryHistoryGet<TData = Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Private Chat History
 */

export function useGetPrivateChatHistoryHistoryGet<TData = Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError = ErrorType<unknown>>(
 params: GetPrivateChatHistoryHistoryGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrivateChatHistoryHistoryGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPrivateChatHistoryHistoryGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Private Chat By Uuid
 */
export const createPrivateChatByUuidCreatePost = (
    params: CreatePrivateChatByUuidCreatePostParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateChatCreateResponse>(
      {url: `/v1/chat/private/create`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getCreatePrivateChatByUuidCreatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrivateChatByUuidCreatePost>>, TError,{params: CreatePrivateChatByUuidCreatePostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPrivateChatByUuidCreatePost>>, TError,{params: CreatePrivateChatByUuidCreatePostParams}, TContext> => {

const mutationKey = ['createPrivateChatByUuidCreatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPrivateChatByUuidCreatePost>>, {params: CreatePrivateChatByUuidCreatePostParams}> = (props) => {
          const {params} = props ?? {};

          return  createPrivateChatByUuidCreatePost(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePrivateChatByUuidCreatePostMutationResult = NonNullable<Awaited<ReturnType<typeof createPrivateChatByUuidCreatePost>>>
    
    export type CreatePrivateChatByUuidCreatePostMutationError = ErrorType<unknown>

    /**
 * @summary Create Private Chat By Uuid
 */
export const useCreatePrivateChatByUuidCreatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPrivateChatByUuidCreatePost>>, TError,{params: CreatePrivateChatByUuidCreatePostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPrivateChatByUuidCreatePost>>,
        TError,
        {params: CreatePrivateChatByUuidCreatePostParams},
        TContext
      > => {
      return useMutation(getCreatePrivateChatByUuidCreatePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Send Private Message With Uuid
 */
export const sendPrivateMessageWithUuidMessageSendPost = (
    privateMessageSendRequest: BodyType<PrivateMessageSendRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateMessageSendResponse>(
      {url: `/v1/chat/private/message/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: privateMessageSendRequest, signal
    },
      options);
    }
  


export const getSendPrivateMessageWithUuidMessageSendPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendPrivateMessageWithUuidMessageSendPost>>, TError,{data: BodyType<PrivateMessageSendRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendPrivateMessageWithUuidMessageSendPost>>, TError,{data: BodyType<PrivateMessageSendRequest>}, TContext> => {

const mutationKey = ['sendPrivateMessageWithUuidMessageSendPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendPrivateMessageWithUuidMessageSendPost>>, {data: BodyType<PrivateMessageSendRequest>}> = (props) => {
          const {data} = props ?? {};

          return  sendPrivateMessageWithUuidMessageSendPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SendPrivateMessageWithUuidMessageSendPostMutationResult = NonNullable<Awaited<ReturnType<typeof sendPrivateMessageWithUuidMessageSendPost>>>
    export type SendPrivateMessageWithUuidMessageSendPostMutationBody = BodyType<PrivateMessageSendRequest>
    export type SendPrivateMessageWithUuidMessageSendPostMutationError = ErrorType<unknown>

    /**
 * @summary Send Private Message With Uuid
 */
export const useSendPrivateMessageWithUuidMessageSendPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendPrivateMessageWithUuidMessageSendPost>>, TError,{data: BodyType<PrivateMessageSendRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendPrivateMessageWithUuidMessageSendPost>>,
        TError,
        {data: BodyType<PrivateMessageSendRequest>},
        TContext
      > => {
      return useMutation(getSendPrivateMessageWithUuidMessageSendPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Private Message
 */
export const deletePrivateMessageMessageDeletePost = (
    privateMessageDeleteRequest: BodyType<PrivateMessageDeleteRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateMessageDeleteResponse>(
      {url: `/v1/chat/private/message/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: privateMessageDeleteRequest, signal
    },
      options);
    }
  


export const getDeletePrivateMessageMessageDeletePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrivateMessageMessageDeletePost>>, TError,{data: BodyType<PrivateMessageDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePrivateMessageMessageDeletePost>>, TError,{data: BodyType<PrivateMessageDeleteRequest>}, TContext> => {

const mutationKey = ['deletePrivateMessageMessageDeletePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePrivateMessageMessageDeletePost>>, {data: BodyType<PrivateMessageDeleteRequest>}> = (props) => {
          const {data} = props ?? {};

          return  deletePrivateMessageMessageDeletePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePrivateMessageMessageDeletePostMutationResult = NonNullable<Awaited<ReturnType<typeof deletePrivateMessageMessageDeletePost>>>
    export type DeletePrivateMessageMessageDeletePostMutationBody = BodyType<PrivateMessageDeleteRequest>
    export type DeletePrivateMessageMessageDeletePostMutationError = ErrorType<unknown>

    /**
 * @summary Delete Private Message
 */
export const useDeletePrivateMessageMessageDeletePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePrivateMessageMessageDeletePost>>, TError,{data: BodyType<PrivateMessageDeleteRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePrivateMessageMessageDeletePost>>,
        TError,
        {data: BodyType<PrivateMessageDeleteRequest>},
        TContext
      > => {
      return useMutation(getDeletePrivateMessageMessageDeletePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Edit Private Message
 */
export const editPrivateMessageMessageEditPut = (
    privateMessageEditRequest: BodyType<PrivateMessageEditRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateMessageEditResponse>(
      {url: `/v1/chat/private/message/edit`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: privateMessageEditRequest, signal
    },
      options);
    }
  


export const getEditPrivateMessageMessageEditPutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editPrivateMessageMessageEditPut>>, TError,{data: BodyType<PrivateMessageEditRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof editPrivateMessageMessageEditPut>>, TError,{data: BodyType<PrivateMessageEditRequest>}, TContext> => {

const mutationKey = ['editPrivateMessageMessageEditPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editPrivateMessageMessageEditPut>>, {data: BodyType<PrivateMessageEditRequest>}> = (props) => {
          const {data} = props ?? {};

          return  editPrivateMessageMessageEditPut(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EditPrivateMessageMessageEditPutMutationResult = NonNullable<Awaited<ReturnType<typeof editPrivateMessageMessageEditPut>>>
    export type EditPrivateMessageMessageEditPutMutationBody = BodyType<PrivateMessageEditRequest>
    export type EditPrivateMessageMessageEditPutMutationError = ErrorType<unknown>

    /**
 * @summary Edit Private Message
 */
export const useEditPrivateMessageMessageEditPut = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editPrivateMessageMessageEditPut>>, TError,{data: BodyType<PrivateMessageEditRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editPrivateMessageMessageEditPut>>,
        TError,
        {data: BodyType<PrivateMessageEditRequest>},
        TContext
      > => {
      return useMutation(getEditPrivateMessageMessageEditPutMutationOptions(options), queryClient);
    }
    /**
 * @summary Mark Private Chat Read
 */
export const markPrivateChatReadMessageMarkReadPost = (
    privateChatMarkReadRequest: BodyType<PrivateChatMarkReadRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateChatMarkReadResponse>(
      {url: `/v1/chat/private/message/mark-read`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: privateChatMarkReadRequest, signal
    },
      options);
    }
  


export const getMarkPrivateChatReadMessageMarkReadPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPrivateChatReadMessageMarkReadPost>>, TError,{data: BodyType<PrivateChatMarkReadRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof markPrivateChatReadMessageMarkReadPost>>, TError,{data: BodyType<PrivateChatMarkReadRequest>}, TContext> => {

const mutationKey = ['markPrivateChatReadMessageMarkReadPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markPrivateChatReadMessageMarkReadPost>>, {data: BodyType<PrivateChatMarkReadRequest>}> = (props) => {
          const {data} = props ?? {};

          return  markPrivateChatReadMessageMarkReadPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type MarkPrivateChatReadMessageMarkReadPostMutationResult = NonNullable<Awaited<ReturnType<typeof markPrivateChatReadMessageMarkReadPost>>>
    export type MarkPrivateChatReadMessageMarkReadPostMutationBody = BodyType<PrivateChatMarkReadRequest>
    export type MarkPrivateChatReadMessageMarkReadPostMutationError = ErrorType<unknown>

    /**
 * @summary Mark Private Chat Read
 */
export const useMarkPrivateChatReadMessageMarkReadPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markPrivateChatReadMessageMarkReadPost>>, TError,{data: BodyType<PrivateChatMarkReadRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markPrivateChatReadMessageMarkReadPost>>,
        TError,
        {data: BodyType<PrivateChatMarkReadRequest>},
        TContext
      > => {
      return useMutation(getMarkPrivateChatReadMessageMarkReadPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Internal Send Private Message With Login
 */
export const internalSendPrivateMessageWithLoginInternalSendPost = (
    internalPrivateMessageSendRequest: BodyType<InternalPrivateMessageSendRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PrivateMessageSendResponse>(
      {url: `/v1/chat/private/internal/send`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalPrivateMessageSendRequest, signal
    },
      options);
    }
  


export const getInternalSendPrivateMessageWithLoginInternalSendPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalSendPrivateMessageWithLoginInternalSendPost>>, TError,{data: BodyType<InternalPrivateMessageSendRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof internalSendPrivateMessageWithLoginInternalSendPost>>, TError,{data: BodyType<InternalPrivateMessageSendRequest>}, TContext> => {

const mutationKey = ['internalSendPrivateMessageWithLoginInternalSendPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof internalSendPrivateMessageWithLoginInternalSendPost>>, {data: BodyType<InternalPrivateMessageSendRequest>}> = (props) => {
          const {data} = props ?? {};

          return  internalSendPrivateMessageWithLoginInternalSendPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InternalSendPrivateMessageWithLoginInternalSendPostMutationResult = NonNullable<Awaited<ReturnType<typeof internalSendPrivateMessageWithLoginInternalSendPost>>>
    export type InternalSendPrivateMessageWithLoginInternalSendPostMutationBody = BodyType<InternalPrivateMessageSendRequest>
    export type InternalSendPrivateMessageWithLoginInternalSendPostMutationError = ErrorType<unknown>

    /**
 * @summary Internal Send Private Message With Login
 */
export const useInternalSendPrivateMessageWithLoginInternalSendPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalSendPrivateMessageWithLoginInternalSendPost>>, TError,{data: BodyType<InternalPrivateMessageSendRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof internalSendPrivateMessageWithLoginInternalSendPost>>,
        TError,
        {data: BodyType<InternalPrivateMessageSendRequest>},
        TContext
      > => {
      return useMutation(getInternalSendPrivateMessageWithLoginInternalSendPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Internal Members Private Chat
 */
export const internalMembersPrivateChatInternalMembersGet = (
    params: InternalMembersPrivateChatInternalMembersGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalPrivateChatMembersResponse>(
      {url: `/v1/chat/private/internal/members`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getInternalMembersPrivateChatInternalMembersGetQueryKey = (params?: InternalMembersPrivateChatInternalMembersGetParams,) => {
    return [
    `/v1/chat/private/internal/members`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getInternalMembersPrivateChatInternalMembersGetQueryOptions = <TData = Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError = ErrorType<unknown>>(params: InternalMembersPrivateChatInternalMembersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalMembersPrivateChatInternalMembersGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>> = ({ signal }) => internalMembersPrivateChatInternalMembersGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalMembersPrivateChatInternalMembersGetQueryResult = NonNullable<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>>
export type InternalMembersPrivateChatInternalMembersGetQueryError = ErrorType<unknown>


export function useInternalMembersPrivateChatInternalMembersGet<TData = Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError = ErrorType<unknown>>(
 params: InternalMembersPrivateChatInternalMembersGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>,
          TError,
          Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalMembersPrivateChatInternalMembersGet<TData = Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError = ErrorType<unknown>>(
 params: InternalMembersPrivateChatInternalMembersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>,
          TError,
          Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalMembersPrivateChatInternalMembersGet<TData = Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError = ErrorType<unknown>>(
 params: InternalMembersPrivateChatInternalMembersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Internal Members Private Chat
 */

export function useInternalMembersPrivateChatInternalMembersGet<TData = Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError = ErrorType<unknown>>(
 params: InternalMembersPrivateChatInternalMembersGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalMembersPrivateChatInternalMembersGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalMembersPrivateChatInternalMembersGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




