/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Auth API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  LoginCodeRequest,
  LoginRequest,
  LoginResponse,
  VerifyCodeRequest
} from '../auth-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Вход по логину и паролю.
 * @summary Login Password
 */
export const loginPasswordLoginPasswordPost = (
    loginRequest: BodyType<LoginRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LoginResponse>(
      {url: `/v1/auth/login/password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginPasswordLoginPasswordPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginPasswordLoginPasswordPost>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginPasswordLoginPasswordPost>>, TError,{data: BodyType<LoginRequest>}, TContext> => {

const mutationKey = ['loginPasswordLoginPasswordPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginPasswordLoginPasswordPost>>, {data: BodyType<LoginRequest>}> = (props) => {
          const {data} = props ?? {};

          return  loginPasswordLoginPasswordPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginPasswordLoginPasswordPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginPasswordLoginPasswordPost>>>
    export type LoginPasswordLoginPasswordPostMutationBody = BodyType<LoginRequest>
    export type LoginPasswordLoginPasswordPostMutationError = ErrorType<unknown>

    /**
 * @summary Login Password
 */
export const useLoginPasswordLoginPasswordPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginPasswordLoginPasswordPost>>, TError,{data: BodyType<LoginRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginPasswordLoginPasswordPost>>,
        TError,
        {data: BodyType<LoginRequest>},
        TContext
      > => {
      return useMutation(getLoginPasswordLoginPasswordPostMutationOptions(options), queryClient);
    }
    /**
 * Отправка OTP кода для входа.
Код отправляется в системный чат при наличии активных сессий.
 * @summary Login Code
 */
export const loginCodeLoginCodePost = (
    loginCodeRequest: BodyType<LoginCodeRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/auth/login/code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginCodeRequest, signal
    },
      options);
    }
  


export const getLoginCodeLoginCodePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, TError,{data: BodyType<LoginCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, TError,{data: BodyType<LoginCodeRequest>}, TContext> => {

const mutationKey = ['loginCodeLoginCodePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, {data: BodyType<LoginCodeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  loginCodeLoginCodePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginCodeLoginCodePostMutationResult = NonNullable<Awaited<ReturnType<typeof loginCodeLoginCodePost>>>
    export type LoginCodeLoginCodePostMutationBody = BodyType<LoginCodeRequest>
    export type LoginCodeLoginCodePostMutationError = ErrorType<unknown>

    /**
 * @summary Login Code
 */
export const useLoginCodeLoginCodePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginCodeLoginCodePost>>, TError,{data: BodyType<LoginCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginCodeLoginCodePost>>,
        TError,
        {data: BodyType<LoginCodeRequest>},
        TContext
      > => {
      return useMutation(getLoginCodeLoginCodePostMutationOptions(options), queryClient);
    }
    /**
 * Проверка OTP кода и получение токенов.
 * @summary Login Verify Code
 */
export const loginVerifyCodeLoginVerifyCodePost = (
    verifyCodeRequest: BodyType<VerifyCodeRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LoginResponse>(
      {url: `/v1/auth/login/verify_code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyCodeRequest, signal
    },
      options);
    }
  


export const getLoginVerifyCodeLoginVerifyCodePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginVerifyCodeLoginVerifyCodePost>>, TError,{data: BodyType<VerifyCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginVerifyCodeLoginVerifyCodePost>>, TError,{data: BodyType<VerifyCodeRequest>}, TContext> => {

const mutationKey = ['loginVerifyCodeLoginVerifyCodePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginVerifyCodeLoginVerifyCodePost>>, {data: BodyType<VerifyCodeRequest>}> = (props) => {
          const {data} = props ?? {};

          return  loginVerifyCodeLoginVerifyCodePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginVerifyCodeLoginVerifyCodePostMutationResult = NonNullable<Awaited<ReturnType<typeof loginVerifyCodeLoginVerifyCodePost>>>
    export type LoginVerifyCodeLoginVerifyCodePostMutationBody = BodyType<VerifyCodeRequest>
    export type LoginVerifyCodeLoginVerifyCodePostMutationError = ErrorType<unknown>

    /**
 * @summary Login Verify Code
 */
export const useLoginVerifyCodeLoginVerifyCodePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginVerifyCodeLoginVerifyCodePost>>, TError,{data: BodyType<VerifyCodeRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginVerifyCodeLoginVerifyCodePost>>,
        TError,
        {data: BodyType<VerifyCodeRequest>},
        TContext
      > => {
      return useMutation(getLoginVerifyCodeLoginVerifyCodePostMutationOptions(options), queryClient);
    }
    