/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * rating_service API
 * OpenAPI spec version: 1.0.0
 */
export interface MessageData {
  message: string;
}

export interface BaseResponse {
  status: string;
  data: MessageData;
}

export interface UserRatingData {
  /** Реальный рейтинг пользователя (0–5) */
  real?: number | null;
  /** Отображаемый рейтинг пользователя (0–5) */
  displayed?: number | null;
}

export interface UserRatingsItem {
  /** ID пользователя */
  user_id: string;
  /** Статус ответа на пользователя */
  status: number;
  /** Рейтинг пользователя */
  rating: UserRatingData;
}

export interface UsersRatingsRequest {
  user_ids: string[];
}

export interface UsersRatingsResponse {
  /** Статус ответа */
  status: string;
  /** Список рейтингов пользователей */
  data: UserRatingsItem[];
}

