/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Profile API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse
} from '../profile-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Ping
 */
export const pingPingGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/profile/ping`, method: 'GET', signal
    },
      options);
    }
  



export const getPingPingGetQueryKey = () => {
    return [
    `/v1/profile/ping`
    ] as const;
    }

    
export const getPingPingGetQueryOptions = <TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPingPingGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pingPingGet>>> = ({ signal }) => pingPingGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PingPingGetQueryResult = NonNullable<Awaited<ReturnType<typeof pingPingGet>>>
export type PingPingGetQueryError = ErrorType<unknown>


export function usePingPingGet<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pingPingGet>>,
          TError,
          Awaited<ReturnType<typeof pingPingGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePingPingGet<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pingPingGet>>,
          TError,
          Awaited<ReturnType<typeof pingPingGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePingPingGet<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ping
 */

export function usePingPingGet<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPingPingGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getPingPingGetSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPingPingGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pingPingGet>>> = ({ signal }) => pingPingGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PingPingGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof pingPingGet>>>
export type PingPingGetSuspenseQueryError = ErrorType<unknown>


export function usePingPingGetSuspense<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePingPingGetSuspense<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePingPingGetSuspense<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ping
 */

export function usePingPingGetSuspense<TData = Awaited<ReturnType<typeof pingPingGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof pingPingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPingPingGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Example Errors From Server
 */
export const exampleErrorsFromServerErrorsGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/profile/errors`, method: 'GET', signal
    },
      options);
    }
  



export const getExampleErrorsFromServerErrorsGetQueryKey = () => {
    return [
    `/v1/profile/errors`
    ] as const;
    }

    
export const getExampleErrorsFromServerErrorsGetQueryOptions = <TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExampleErrorsFromServerErrorsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>> = ({ signal }) => exampleErrorsFromServerErrorsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExampleErrorsFromServerErrorsGetQueryResult = NonNullable<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>>
export type ExampleErrorsFromServerErrorsGetQueryError = ErrorType<unknown>


export function useExampleErrorsFromServerErrorsGet<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>,
          TError,
          Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExampleErrorsFromServerErrorsGet<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>,
          TError,
          Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExampleErrorsFromServerErrorsGet<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Example Errors From Server
 */

export function useExampleErrorsFromServerErrorsGet<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExampleErrorsFromServerErrorsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getExampleErrorsFromServerErrorsGetSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExampleErrorsFromServerErrorsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>> = ({ signal }) => exampleErrorsFromServerErrorsGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExampleErrorsFromServerErrorsGetSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>>
export type ExampleErrorsFromServerErrorsGetSuspenseQueryError = ErrorType<unknown>


export function useExampleErrorsFromServerErrorsGetSuspense<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExampleErrorsFromServerErrorsGetSuspense<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExampleErrorsFromServerErrorsGetSuspense<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Example Errors From Server
 */

export function useExampleErrorsFromServerErrorsGetSuspense<TData = Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof exampleErrorsFromServerErrorsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExampleErrorsFromServerErrorsGetSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




