/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * achievement_service API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BaseResponse,
  InternalAchievementListInternalListGetParams,
  InternalAchievementListResponse,
  InternalAchievementProgressUpdateRequest,
  InternalAchievementProgressUpdateResponse,
  InternalAchievementUpdateAllRequest,
  PublicAchievementListResponse
} from '../achievement-service.schemas';

import { customInstance } from '../../../axios-client';
import type { ErrorType , BodyType } from '../../../axios-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Внутренний метод для обновления прогресса по ачивке.
 * @summary Internal Achievement Progress Update
 */
export const internalAchievementProgressUpdateInternalProgressUpdatePost = (
    internalAchievementProgressUpdateRequest: BodyType<InternalAchievementProgressUpdateRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalAchievementProgressUpdateResponse>(
      {url: `/v1/achievement/internal/progress-update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalAchievementProgressUpdateRequest, signal
    },
      options);
    }
  


export const getInternalAchievementProgressUpdateInternalProgressUpdatePostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalAchievementProgressUpdateInternalProgressUpdatePost>>, TError,{data: BodyType<InternalAchievementProgressUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof internalAchievementProgressUpdateInternalProgressUpdatePost>>, TError,{data: BodyType<InternalAchievementProgressUpdateRequest>}, TContext> => {

const mutationKey = ['internalAchievementProgressUpdateInternalProgressUpdatePost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof internalAchievementProgressUpdateInternalProgressUpdatePost>>, {data: BodyType<InternalAchievementProgressUpdateRequest>}> = (props) => {
          const {data} = props ?? {};

          return  internalAchievementProgressUpdateInternalProgressUpdatePost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InternalAchievementProgressUpdateInternalProgressUpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof internalAchievementProgressUpdateInternalProgressUpdatePost>>>
    export type InternalAchievementProgressUpdateInternalProgressUpdatePostMutationBody = BodyType<InternalAchievementProgressUpdateRequest>
    export type InternalAchievementProgressUpdateInternalProgressUpdatePostMutationError = ErrorType<unknown>

    /**
 * @summary Internal Achievement Progress Update
 */
export const useInternalAchievementProgressUpdateInternalProgressUpdatePost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalAchievementProgressUpdateInternalProgressUpdatePost>>, TError,{data: BodyType<InternalAchievementProgressUpdateRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof internalAchievementProgressUpdateInternalProgressUpdatePost>>,
        TError,
        {data: BodyType<InternalAchievementProgressUpdateRequest>},
        TContext
      > => {
      return useMutation(getInternalAchievementProgressUpdateInternalProgressUpdatePostMutationOptions(options), queryClient);
    }
    /**
 * Внутренний метод для обновления прогресса по ачивке.
 * @summary Internal Achievement Update All
 */
export const internalAchievementUpdateAllInternalUpdateAllPost = (
    internalAchievementUpdateAllRequest: BodyType<InternalAchievementUpdateAllRequest>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<BaseResponse>(
      {url: `/v1/achievement/internal/update-all`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: internalAchievementUpdateAllRequest, signal
    },
      options);
    }
  


export const getInternalAchievementUpdateAllInternalUpdateAllPostMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalAchievementUpdateAllInternalUpdateAllPost>>, TError,{data: BodyType<InternalAchievementUpdateAllRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof internalAchievementUpdateAllInternalUpdateAllPost>>, TError,{data: BodyType<InternalAchievementUpdateAllRequest>}, TContext> => {

const mutationKey = ['internalAchievementUpdateAllInternalUpdateAllPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof internalAchievementUpdateAllInternalUpdateAllPost>>, {data: BodyType<InternalAchievementUpdateAllRequest>}> = (props) => {
          const {data} = props ?? {};

          return  internalAchievementUpdateAllInternalUpdateAllPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type InternalAchievementUpdateAllInternalUpdateAllPostMutationResult = NonNullable<Awaited<ReturnType<typeof internalAchievementUpdateAllInternalUpdateAllPost>>>
    export type InternalAchievementUpdateAllInternalUpdateAllPostMutationBody = BodyType<InternalAchievementUpdateAllRequest>
    export type InternalAchievementUpdateAllInternalUpdateAllPostMutationError = ErrorType<unknown>

    /**
 * @summary Internal Achievement Update All
 */
export const useInternalAchievementUpdateAllInternalUpdateAllPost = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof internalAchievementUpdateAllInternalUpdateAllPost>>, TError,{data: BodyType<InternalAchievementUpdateAllRequest>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof internalAchievementUpdateAllInternalUpdateAllPost>>,
        TError,
        {data: BodyType<InternalAchievementUpdateAllRequest>},
        TContext
      > => {
      return useMutation(getInternalAchievementUpdateAllInternalUpdateAllPostMutationOptions(options), queryClient);
    }
    /**
 * Внутренний метод — полный список ачивок для конкретного пользователя.
 * @summary Internal Achievement List
 */
export const internalAchievementListInternalListGet = (
    params: InternalAchievementListInternalListGetParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<InternalAchievementListResponse>(
      {url: `/v1/achievement/internal/list`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getInternalAchievementListInternalListGetQueryKey = (params?: InternalAchievementListInternalListGetParams,) => {
    return [
    `/v1/achievement/internal/list`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getInternalAchievementListInternalListGetQueryOptions = <TData = Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError = ErrorType<unknown>>(params: InternalAchievementListInternalListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInternalAchievementListInternalListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>> = ({ signal }) => internalAchievementListInternalListGet(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InternalAchievementListInternalListGetQueryResult = NonNullable<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>>
export type InternalAchievementListInternalListGetQueryError = ErrorType<unknown>


export function useInternalAchievementListInternalListGet<TData = Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError = ErrorType<unknown>>(
 params: InternalAchievementListInternalListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalAchievementListInternalListGet>>,
          TError,
          Awaited<ReturnType<typeof internalAchievementListInternalListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalAchievementListInternalListGet<TData = Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError = ErrorType<unknown>>(
 params: InternalAchievementListInternalListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof internalAchievementListInternalListGet>>,
          TError,
          Awaited<ReturnType<typeof internalAchievementListInternalListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInternalAchievementListInternalListGet<TData = Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError = ErrorType<unknown>>(
 params: InternalAchievementListInternalListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Internal Achievement List
 */

export function useInternalAchievementListInternalListGet<TData = Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError = ErrorType<unknown>>(
 params: InternalAchievementListInternalListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof internalAchievementListInternalListGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInternalAchievementListInternalListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Публичный метод — достижения текущего пользователя.
 * @summary Get My Achievements
 */
export const getMyAchievementsMyGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PublicAchievementListResponse>(
      {url: `/v1/achievement/my`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMyAchievementsMyGetQueryKey = () => {
    return [
    `/v1/achievement/my`
    ] as const;
    }

    
export const getGetMyAchievementsMyGetQueryOptions = <TData = Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyAchievementsMyGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyAchievementsMyGet>>> = ({ signal }) => getMyAchievementsMyGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyAchievementsMyGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMyAchievementsMyGet>>>
export type GetMyAchievementsMyGetQueryError = ErrorType<unknown>


export function useGetMyAchievementsMyGet<TData = Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyAchievementsMyGet>>,
          TError,
          Awaited<ReturnType<typeof getMyAchievementsMyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyAchievementsMyGet<TData = Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyAchievementsMyGet>>,
          TError,
          Awaited<ReturnType<typeof getMyAchievementsMyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyAchievementsMyGet<TData = Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Achievements
 */

export function useGetMyAchievementsMyGet<TData = Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAchievementsMyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyAchievementsMyGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Публичный метод — достижения другого пользователя.
Секретные скрываем.
 * @summary Get User Achievements
 */
export const getUserAchievementsUserUserIdGet = (
    userId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PublicAchievementListResponse>(
      {url: `/v1/achievement/user/${userId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUserAchievementsUserUserIdGetQueryKey = (userId: string,) => {
    return [
    `/v1/achievement/user/${userId}`
    ] as const;
    }

    
export const getGetUserAchievementsUserUserIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError = ErrorType<unknown>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserAchievementsUserUserIdGetQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>> = ({ signal }) => getUserAchievementsUserUserIdGet(userId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserAchievementsUserUserIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>>
export type GetUserAchievementsUserUserIdGetQueryError = ErrorType<unknown>


export function useGetUserAchievementsUserUserIdGet<TData = Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserAchievementsUserUserIdGet<TData = Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserAchievementsUserUserIdGet<TData = Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Achievements
 */

export function useGetUserAchievementsUserUserIdGet<TData = Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError = ErrorType<unknown>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserAchievementsUserUserIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserAchievementsUserUserIdGetQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




