// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "achievement": {
    "badge": {
      "bronze": "Bronze",
      "diamond": "Diamond",
      "gold": "Gold",
      "legendary": "Legendary",
      "platinum": "Platinum",
      "silver": "Silver"
    },
    "clear_filters": "Clear filters",
    "completed_with_date": "Completed: {{date}}",
    "empty": "No achievements yet",
    "empty_filtered": "No achievements match selected filters",
    "load_error": "Failed to load achievements",
    "loading": "Loading achievements...",
    "progress": "Progress: {{progress}}/{{required}}",
    "search_placeholder": "Search by name or description",
    "status": {
      "completed": "Completed",
      "in_progress": "In progress"
    }
  },
  "api-errors": {
    "contact_update": "Couldn't update contact"
  },
  "auth": {
    "enter": "Login",
    "enter_to_account_for_communicate_friend": "Log in to your account to continue chatting with your friends",
    "glad_see_you": "We are glad to see you",
    "have_account": "You have account?",
    "invalid_login": "Invalid login",
    "invalid_message_login": "Invalid login. Please retry",
    "register": "Register",
    "return_to_yobble": "Yobble"
  },
  "button-labels": {
    "add": "Add",
    "back": "Back",
    "cancel": "Cancel",
    "close": "Close",
    "confirm": "Confirm",
    "create": "Create",
    "delete": "Delete",
    "edit": "Edit",
    "enter": "Enter",
    "exit": "Exit",
    "next": "Next",
    "register": "Register",
    "remove": "Remove",
    "retray": "Retray",
    "save": "Save",
    "submit": "Send"
  },
  "chat": {
    "empty-description": "Send the first message to start the conversation.",
    "empty-title": "No messages yet",
    "input-placeholder": "Message...",
    "send-message": "Send message"
  },
  "contact": {
    "add": "Add",
    "block": "Block",
    "contact-blocked-you": "{{username}} blocked you",
    "contact-remove-pending": "Removing...",
    "contact-remove-success": "Contact removed",
    "contacts": "Contacts",
    "contacts-empty": "You do not have any contacts yet. Add them via search.",
    "contacts-load-error": "An unexpected error occurred while loading contacts. Please reload the page.",
    "current-user-in-contact-target": "You are in this user's contacts",
    "error-contact-operation": "Contact operation error",
    "error-contact-operation-message": "Failed to update contact. Please try again.",
    "in-contact": "In contacts",
    "mutal-blocked": "You are mutually blocked",
    "relations": "Relations",
    "you-block-user": "You blocked {{username}}",
    "yours-not-have-relation": "You have no relation"
  },
  "contact-menu": {
    "blacklist-add": "Add to blacklist",
    "contact": "Contact",
    "contact-add": "Add to contacts",
    "contact-edit": "Edit contact",
    "contact-remove": "Remove from contacts",
    "from-blacklist-remove": "Remove from blacklist"
  },
  "days": {
    "today": "Today"
  },
  "errors-boundary": {
    "copied": "Copied",
    "copy": "Copy",
    "retry": "Retry",
    "title": "Something went wrong",
    "unknown-error": "Unknown error"
  },
  "field-labels": {
    "bio_label": "Biography",
    "full-name": "Full name",
    "password_label": "Password",
    "password_repeat_label": "Repeat password",
    "userName_label": "User name"
  },
  "lists": {
    "empty": "The list is empty",
    "empty-filtered": "No items match the selected filters",
    "empty-search": "No items found for your query",
    "error": "Failed to load the list",
    "items-count": "Items: {{count}}",
    "load-more": "Load more",
    "load-more-loading": "Loading more...",
    "loading": "Loading list...",
    "refresh": "Refresh list",
    "retry": "Retry loading",
    "selected": "Selected: {{count}}",
    "title": "List"
  },
  "navbar": {
    "achievements": "Achievements",
    "block-users": "Blocked users",
    "change-password": "Change password",
    "contacts": "Contacts",
    "interface_edit": "Interface",
    "main": "Home",
    "profile": "Profile",
    "profile_edit": "Edit profile",
    "profile_settings": "Privacy",
    "search": "Search",
    "sessions": "Sessions",
    "settings": "Settings",
    "settings/interface": "Interface",
    "settings/permissions": "Permissions",
    "settings/sessions": "Sessions",
    "submit-logout-text": "Are you sure you want to get out?"
  },
  "password-change": {
    "button-change": "Change",
    "button-changed": "Changed",
    "modal-title": "Change password",
    "new-password": "New password",
    "notification-loading-title": "Updating password",
    "notification-success-message": "Password updated successfully!",
    "old-password": "Old password"
  },
  "permisions": {
    "allow_message_forwarding": "Allow message forwarding",
    "allow_messages_from_non_contacts": "Accept messages from strangers",
    "allow_server_chats": "Allow chats to be stored on the server",
    "auto_delete_after_days": "Auto‑delete account after X days",
    "call_permission": "Who can call you",
    "contacts": "Contacts",
    "do_not_delete": "Do not delete",
    "everyone": "Everyone",
    "force_auto_delete_messages_in_private": "Force auto‑delete in private chats",
    "group_invite_permission": "Who can invite to conversations",
    "is_searchable": "Can users find you",
    "last_seen_visibility": "Who can see 'last seen'",
    "max_message_auto_delete_seconds": "Maximum message auto‑delete timer",
    "nobody": "Nobody",
    "public_invite_permission": "Who can invite to public groups",
    "show_bio_to_non_contacts": "Show bio to non‑contacts",
    "show_profile_photo_to_non_contacts": "Show photo to non‑contacts",
    "show_stories_to_non_contacts": "Show stories to non‑contacts",
    "title": "Privacy settings"
  },
  "plurar-data": {
    "days_one": "{{count}} day",
    "days_other": "{{count}} days",
    "days_zero": "",
    "hours_one": "{{count}} hour",
    "hours_other": "{{count}} hours",
    "hours_zero": ""
  },
  "profile": {
    "bio": "Biography",
    "bio-undefined": "Biography is not set",
    "bio-user-not-write-about-himself": "User did not fill in biography",
    "created_at": "Created at",
    "full-name": "Full name",
    "full-name-undefined": "Full name is not set",
    "full-name-user-not-write-himself-name": "User did not specify a full name",
    "login": "Login",
    "mutal-contacts": "You are mutual contacts",
    "put_profile_error": "Profile change failed",
    "put_success": "The changes have been applied",
    "rating": "Rating",
    "verified": "Verified",
    "you-friends": "You are friends"
  },
  "search": {
    "clear-history": "Clear history",
    "history": "History",
    "history-empty": "History is empty",
    "search-placeholder": "Search"
  },
  "session": {
    "close_all_sessions": "Close all sessions",
    "close_session": "Close session",
    "created_at": "Created at",
    "last_activation": "Last actiovation",
    "revoke_text_all": "Are you sure you want to end all sessions except the current one?",
    "revoke_text_one": "Are you sure you want to end the selected session?",
    "revoke_title_one": "Session termination",
    "sessions_not_found": "No active sessions",
    "untrasted_session": "An untrusted session is any session that is less than 5 days old. This session cannot terminate other sessions."
  },
  "settings-tab": {
    "animation-error": "Animation selection error",
    "animation-error-message": "Failed to apply the selected animation",
    "animation-speed": "Animation speed",
    "animation-speed-fast": "Fast",
    "animation-speed-normal": "Normal",
    "animation-speed-smoothly": "Smooth",
    "animation-speed-super-smoothly": "Very smooth",
    "animations": "Animations",
    "animations-label": "Animation type",
    "blue": "Blue",
    "gray": "Gray",
    "green": "Green",
    "indigo": "Indigo",
    "keyframes": "Linear",
    "language-select": "Application language",
    "logout": "Log out",
    "primary-color-label": "Primary application color",
    "primary-color-not-exist": "The selected color does not exist. The application color was not changed",
    "primary-color-not-exist-title": "Invalid color",
    "radius": "Corner radius",
    "radius-size-lg": "Large (lg)",
    "radius-size-md": "Medium (md)",
    "radius-size-sm": "Small (sm)",
    "radius-size-xl": "Extra large (xl)",
    "radius-size-xs": "Extra small (xs)",
    "red": "Red",
    "reset": "Reset",
    "spring": "Spring",
    "theme-category": "Theme",
    "theme-option-auto": "Auto",
    "theme-option-dark": "Dark",
    "theme-option-light": "Light",
    "violet": "Violet",
    "with-animation-label": "Animations across the app",
    "with-animations-description": "Enables or disables animations on all app screens and UI elements"
  },
  "side-bar": {
    "dark_theme": "Dark theme"
  },
  "titles": {
    "error": "Error",
    "not_found_page": "Page not found",
    "please_check_address": "Please check the address and repeat",
    "success": "Success"
  },
  "update-contact": {
    "custom-name": "Custom name",
    "save": "Save"
  }
}

export default Resources;
