/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTestRouteImport } from './routes/auth/test'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthModeRouteImport } from './routes/auth/$mode'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthModeRoute = AuthModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/$mode': typeof AuthModeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/$mode': typeof AuthModeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/$mode': typeof AuthModeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/test': typeof AuthTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/auth/$mode'
    | '/auth/login'
    | '/auth/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/about' | '/auth/$mode' | '/auth/login' | '/auth/test'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/about'
    | '/auth/$mode'
    | '/auth/login'
    | '/auth/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/test': {
      id: '/auth/test'
      path: '/test'
      fullPath: '/auth/test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/$mode': {
      id: '/auth/$mode'
      path: '/$mode'
      fullPath: '/auth/$mode'
      preLoaderRoute: typeof AuthModeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthModeRoute: typeof AuthModeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthTestRoute: typeof AuthTestRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthModeRoute: AuthModeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthTestRoute: AuthTestRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
